//Copyright SimBlocks LLC 2016-2026
/**
 * @file HostEmulatorDefinitions.h
 * @brief Core definitions and global structures for the HostEmulator application.
 *
 * Provides widget IDs for the HostEmulator GUI and global settings structure for host-side simulation integration.
 * Integrates with wxWidgets for GUI event handling and the SimBlocks SDK for host and view management.
 *
 * @see EnumWidgetID
 * @see SHostEmulatorGlobals
 * @see sbio::cigi::host::CHostViewManager
 */
#pragma once
#ifndef SIMBLOCKS_HOST_EMULATOR_DEFINITIONS_H
#define SIMBLOCKS_HOST_EMULATOR_DEFINITIONS_H

#include <wx/wx.h>
#include "GlobalHeaders/Globals.h"
#include "HostCigiLib/HostCigiLibDeclarations.h"

/**
 * @brief Widget IDs for HostEmulator GUI components and events.
 */
enum EnumWidgetID
{
  ID_HOST_UPDATE_TIMER = wxID_HIGHEST + 1,
  ID_GUI_UPDATE_TIMER,

  ID_MENU_LAUNCH_IG,

  ID_NOTEBOOK,

  ID_PACKETS_PAGE_PACKET_TYPE_LIST_BOX,

  ID_ACCELERATION_CONTROL_SEND_PACKET,
  ID_ANIMATION_CONTROL_SEND_PACKET,
  ID_ARTICULATED_PART_CONTROL_SEND_PACKET,
  ID_ATMOSPHERE_CONTROL_SEND_PACKET,
  ID_CELESTIAL_SPHERE_CONTROL_SEND_PACKET,
  ID_COLLISION_DETECTION_SEGMENT_DEFINITION_PACKET,
  ID_COLLISION_DETECTION_VOLUME_DEFINITION_PACKET,
  ID_COLLISION_DETECTION_VOLUME_TYPE_RADIO_BUTTON_EVENT,
  ID_COMPONENT_CONTROL_SEND_PACKET,
  ID_CONFORMAL_CLAMPED_ENTITY_SEND_PACKET,
  ID_ENTITY_CONTROL_ENTITY_TYPE,
  ID_ENTITY_CONTROL_SEND_PACKET,
  ID_ENVIRONMENTAL_REGION_CONTROL_SEND_PACKET,
  ID_ERROR_LOG_CLEAR,
  ID_HAT_HOT_REQUEST_SEND_PACKET,
  ID_HAT_HOT_ID_RADIO_BUTTON_EVENT,
  ID_HAT_HOT_COORDINATE_SYSTEM_RADIO_BUTTON_EVENT,
  ID_IG_CONTROL_SEND_PACKET,
  ID_EARTH_REFERENCE_DEFINITION_SEND_PACKET,
  ID_ENTITY_POSITION_ATTACH_STATE,
  ID_ENTITY_POSITION_SEND_PACKET,
  ID_ENVIRONMENTAL_CONDITIONS_REQUEST_PACKET,
  ID_LINE_OF_SIGHT_SEGMENT_REQUEST_SEND_PACKET,
  ID_LINE_OF_SIGHT_SEGMENT_REQUEST_SOURCE_POINT_COORDINATE_SYSTEM_EVENT,
  ID_LINE_OF_SIGHT_SEGMENT_REQUEST_DESTINATION_POINT_COORDINATE_SYSTEM_EVENT,
  ID_LINE_OF_SIGHT_SEGMENT_REQUEST_RESPONSE_COORDINATE_SYSTEM_EVENT,
  ID_LINE_OF_SIGHT_VECTOR_REQUEST_SEND_PACKET,
  ID_LINE_OF_SIGHT_VECTOR_REQUEST_SOURCE_POINT_COORDINATE_SYSTEM_EVENT,
  ID_LINE_OF_SIGHT_VECTOR_REQUEST_RESPONSE_COORDINATE_SYSTEM_EVENT,
  ID_MARITIME_SURFACE_CONTROL_SEND_PACKET,
  ID_MESSAGE_LOG_CLEAR,
  ID_MOTION_TRACKER_CONTROL_SEND_PACKET,
  ID_MOTION_TRACKER_CONTROL_RADIO_BUTTON_EVENT,
  ID_POSITION_REQUEST_SEND_PACKET,
  ID_SENSOR_CONTROL_SEND_PACKET,
  ID_SHORT_ARTICULATED_CONTROL_SEND_PACKET,
  ID_SHORT_COMPONENT_CONTROL_SEND_PACKET,
  ID_SYMBOL_CIRCLE_DEFINITION_SEND_PACKET,
  ID_SYMBOL_CIRCLE_DEFINITION_ADD_ROW,
  ID_SYMBOL_CIRCLE_CLEAR_ROWS,
  ID_SYMBOL_CLONE_SEND_PACKET,
  ID_SYMBOL_CONTROL_SEND_PACKET,
  ID_SYMBOL_POLYGON_DEFINITION_ADD_ROW,
  ID_SYMBOL_POLYGON_DEFINITION_CLEAR_ROWS,
  ID_SYMBOL_POLYGON_DEFINITION_SEND_PACKET,
  ID_SHORT_SYMBOL_CONTROL_SEND_PACKET,
  ID_SYMBOL_SURFACE_DEFINITION_SEND_PACKET,
  ID_SYMBOL_SURFACE_DEFINITION_ENTITY_VIEW_ID_RADIO_BUTTON_EVENT,
  ID_SYMBOL_TEXT_DEFINITION_SEND_PACKET,
  ID_SYMBOL_TEXT_DEFINITION_FONT_CATEGORY,
  ID_SYMBOL_TEXTURED_CIRCLE_DEFINITION_ADD_ROW,
  ID_SYMBOL_TEXTURED_CIRCLE_CLEAR_ROWS,
  ID_SYMBOL_TEXTURED_CIRCLE_DEFINITION_SEND_PACKET,
  ID_SYMBOL_TEXTURED_POLYGON_DEFINITION_ADD_ROW,
  ID_SYMBOL_TEXTURED_POLYGON_DEFINITION_CLEAR_ROWS,
  ID_SYMBOL_TEXTURED_POLYGON_DEFINITION_SEND_PACKET,
  ID_TERRESTRIAL_SURFACE_CONDITION_SEND_PACKET,
  ID_VELOCITY_CONTROL_SEND_PACKET,
  ID_VIEW_CONTROL_SEND_PACKET,
  ID_VIEW_DEFINITION_PACKET,
  ID_WAVE_CONTROL_SEND_PACKET,
  ID_WEATHER_CONTROL_SEND_PACKET,
  ID_SCRIPTS_PAGE_CATEGORY_COMBO_BOX,
  ID_SCRIPTS_PAGE_LIST_BOX,
  ID_EDIT_SCRIPT_BUTTON,
  ID_RUN_SCRIPT_BUTTON,
  ID_STOP_SCRIPT_BUTTON,
  ID_MESSAGE_PAGE,
  ID_ERROR_PAGE,
};

/**
 * @brief Global settings for the HostEmulator application, including view manager pointer.
 */
struct SHostEmulatorGlobals : sbio::SGlobals
{
  std::shared_ptr<sbio::cigi::host::CHostViewManager> pViewManager;///< Pointer to host view manager
};

#endif
//The source code in this file is licensed under the MIT License. See the LICENSE text file for full terms.
//Refer all inquiries to sales@simblocks.io
//Copyright SimBlocks LLC 2016-2026
