//Copyright SimBlocks LLC 2016-2026
#include "EngineLib.h"
#include "GlobalHeaders/Globals.h"

using namespace sbio;
using namespace sbio::entity;
using namespace sbio::engine;
using namespace sbio::math;
using namespace sbio::ig;

SEngineLibGlobals g_EngineLibGlobals;

void InitEngineLib(const SGlobals& globals, const SEngineLibParams& params)
{
  g_EngineLibGlobals.pLogger = globals.pLogger;
  g_EngineLibGlobals.pImageGeneratorEventMessenger = params.pEventMessenger;
}

void UninitEngineLib()
{
  g_EngineLibGlobals.pLogger = nullptr;
  g_EngineLibGlobals.pImageGeneratorEventMessenger = nullptr;
}

//Vec3Body is the same as BodyCoordinates. It is generated by CigiMessages.idl
/*BodyCoordinates ConvertVec3BodyToBodyCoordinates(sbio::ig::Vec3Body vec3bodyCoordinates)
{
  BodyCoordinates bodyCoordinates;
  bodyCoordinates[0] = vec3bodyCoordinates.X;
  bodyCoordinates[1] = vec3bodyCoordinates.Y;
  bodyCoordinates[2] = vec3bodyCoordinates.Z;

  return bodyCoordinates;
}

sbio::ig::Vec3Body ConvertBodyCoordinatesToVec3Body(sbio::math::BodyCoordinates bodyCoordinates)
{
  Vec3Body vec3Body;
  vec3Body.X = bodyCoordinates[0];
  vec3Body.Y = bodyCoordinates[1];
  vec3Body.Z = bodyCoordinates[2];

  return vec3Body;
}*/
//The source code in this file is licensed under the MIT License. See the LICENSE text file for full terms.
//Refer all inquiries to sales@simblocks.io
//Copyright SimBlocks LLC 2016-2026
