//Copyright SimBlocks LLC 2016-2026
//This file has been generated by idlgen.exe. Do not modify this file directly!
#pragma once
#ifndef SIMBLOCKS_I_IMAGE_GENERATOR_EVENT_MESSENGER_H
#define SIMBLOCKS_I_IMAGE_GENERATOR_EVENT_MESSENGER_H

#include "EngineLib/ImageGeneratorMessages.h"
#include "GlobalHeaders/CommonTypes.h"

namespace sbio
{
  namespace ig
  {
    struct IImageGeneratorEventHandler
    {
    public:
      virtual ~IImageGeneratorEventHandler() {};

      virtual bool IsPointInEntityVolume(const sbio::math::GeocentricCoordinates& point, sbio::EntityID entityID) const = 0;
      virtual void OnCreateEntityMessage(const sbio::ig::entity::SCreateEntityMessage& data) = 0;
      virtual void OnDestroyEntityMessage(const sbio::ig::entity::SDestroyEntityMessage& data) = 0;
      virtual void OnUpdateTopLevelEntityTransformMessage(const sbio::ig::entity::SUpdateTopLevelEntityTransformMessage& data) = 0;
      virtual void OnUpdateChildEntityTransformMessage(const sbio::ig::entity::SUpdateChildEntityTransformMessage& data) = 0;
      virtual void OnSetEntityAttachedMessage(const sbio::ig::entity::SSetEntityAttachedMessage& data) = 0;
      virtual void OnSetEntityActiveMessage(const sbio::ig::entity::SSetEntityActiveMessage& data) = 0;
      virtual void OnSetEntityUnattachedMessage(const sbio::ig::entity::SSetEntityUnattachedMessage& data) = 0;
      virtual void OnSetEntityComponentStateMessage(const sbio::ig::entity::SSetEntityComponentStateMessage& data) = 0;
      virtual void OnUpdateArticulatedPartTransformMessage(const sbio::ig::entity::SUpdateArticulatedPartTransformMessage& data) = 0;
      virtual void OnSetArticulatedPartVisibleMessage(const sbio::ig::entity::SSetArticulatedPartVisibleMessage& data) = 0;
      virtual void OnSetEntityAlphaMessage(const sbio::ig::entity::SSetEntityAlphaMessage& data) = 0;
      virtual void OnSetEntityCollisionDetectionEnabledMessage(const sbio::ig::entity::SSetEntityCollisionDetectionEnabledMessage& data) = 0;
      virtual void OnLineOfSightSegmentRequestBasicMessage(const sbio::ig::terrain::SLineOfSightSegmentRequestBasicMessage& data) = 0;
      virtual void OnLineOfSightSegmentRequestExtendedMessage(const sbio::ig::terrain::SLineOfSightSegmentRequestExtendedMessage& data) = 0;
      virtual void OnLineOfSightVectorRequestBasicMessage(const sbio::ig::terrain::SLineOfSightVectorRequestBasicMessage& data) = 0;
      virtual void OnLineOfSightVectorRequestExtendedMessage(const sbio::ig::terrain::SLineOfSightVectorRequestExtendedMessage& data) = 0;
      virtual void OnHeightAboveTerrainRequestMessage(const sbio::ig::terrain::SHeightAboveTerrainRequestMessage& data) = 0;
      virtual void OnHeightOfTerrainRequestMessage(const sbio::ig::terrain::SHeightOfTerrainRequestMessage& data) = 0;
      virtual void OnTerrestrialSurfaceConditionsChangedMessage() = 0;
      virtual void OnSetRegionalTerrainSurfaceComponentStateMessage(const sbio::ig::terrain::SSetRegionalTerrainSurfaceComponentStateMessage& data) = 0;
      virtual void OnSetGlobalTerrainComponentStateMessage(const sbio::ig::terrain::SSetGlobalTerrainComponentStateMessage& data) = 0;
      virtual void OnSetCollisionDetectionSegmentEnabledMessage(const sbio::ig::physics::SSetCollisionDetectionSegmentEnabledMessage& data) = 0;
      virtual void OnSetCollisionDetectionSegmentMessage(const sbio::ig::physics::SSetCollisionDetectionSegmentMessage& data) = 0;
      virtual void OnCreateCollisionDetectionSegmentMessage(const sbio::ig::physics::SCreateCollisionDetectionSegmentMessage& data) = 0;
      virtual void OnCreateCollisionVolumeSphereMessage(const sbio::ig::physics::SCreateCollisionVolumeSphereMessage& data) = 0;
      virtual void OnCreateCollisionVolumeCuboidMessage(const sbio::ig::physics::SCreateCollisionVolumeCuboidMessage& data) = 0;
      virtual void OnSetCollisionVolumeEnabledMessage(const sbio::ig::physics::SSetCollisionVolumeEnabledMessage& data) = 0;
      virtual void OnSetCollisionVolumeMessage(const sbio::ig::physics::SSetCollisionVolumeMessage& data) = 0;
      virtual void OnDestroyCollisionVolumeMessage(const sbio::ig::physics::SDestroyCollisionVolumeMessage& data) = 0;
      virtual void OnUpdateAttachedCameraTransformMessage(const sbio::ig::view::SUpdateAttachedCameraTransformMessage& data) = 0;
      virtual void OnSetCameraAttachedToEntityMessage(const sbio::ig::view::SSetCameraAttachedToEntityMessage& data) = 0;
      virtual void OnSetCameraUnattachedMessage(const sbio::ig::view::SSetCameraUnattachedMessage& data) = 0;
      virtual void OnSetCameraProjectionMessage(const sbio::ig::view::SSetCameraProjectionMessage& data) = 0;
      virtual void OnSetViewComponentStateMessage(const sbio::ig::view::SSetViewComponentStateMessage& data) = 0;
      virtual void OnSetViewGroupComponentStateMessage(const sbio::ig::view::SSetViewGroupComponentStateMessage& data) = 0;
      virtual void OnLoadDatabaseMessage(const sbio::ig::database::SLoadDatabaseMessage& data) = 0;
      virtual void OnUnloadDatabaseMessage() = 0;
      virtual void OnSetAnimationDirectionMessage(const sbio::ig::animation::SSetAnimationDirectionMessage& data) = 0;
      virtual void OnSetAnimationLoopModeMessage(const sbio::ig::animation::SSetAnimationLoopModeMessage& data) = 0;
      virtual void OnSetAnimationSpeedMessage(const sbio::ig::animation::SSetAnimationSpeedMessage& data) = 0;
      virtual void OnStopEntityAnimationMessage(const sbio::ig::animation::SStopEntityAnimationMessage& data) = 0;
      virtual void OnStopAtCurrentFrameEntityAnimationMessage(const sbio::ig::animation::SStopAtCurrentFrameEntityAnimationMessage& data) = 0;
      virtual void OnPauseEntityAnimationMessage(const sbio::ig::animation::SPauseEntityAnimationMessage& data) = 0;
      virtual void OnPlayEntityAnimationMessage(const sbio::ig::animation::SPlayEntityAnimationMessage& data) = 0;
      virtual void OnRestartEntityAnimationMessage(const sbio::ig::animation::SRestartEntityAnimationMessage& data) = 0;
      virtual void OnCreateSymbolTextMessage(const sbio::ig::symbol::SCreateSymbolTextMessage& data) = 0;
      virtual void OnUpdateSymbolTextMessage(const sbio::ig::symbol::SUpdateSymbolTextMessage& data) = 0;
      virtual void OnSetSymbolColorMessage(const sbio::ig::symbol::SSetSymbolColorMessage& data) = 0;
      virtual void OnDestroySymbolMessage(const sbio::ig::symbol::SDestroySymbolMessage& data) = 0;
      virtual void OnCreateSymbolCircleMessage(const sbio::ig::symbol::SCreateSymbolCircleMessage& data) = 0;
      virtual void OnUpdateSymbolCircleMessage(const sbio::ig::symbol::SUpdateSymbolCircleMessage& data) = 0;
      virtual void OnUpdateSymbolCircleElementMessage(const sbio::ig::symbol::SUpdateSymbolCircleElementMessage& data) = 0;
      virtual void OnUpdateSymbolCircleFilledMessage(const sbio::ig::symbol::SUpdateSymbolCircleFilledMessage& data) = 0;
      virtual void OnUpdateSymbolCircleFilledElementMessage(const sbio::ig::symbol::SUpdateSymbolCircleFilledElementMessage& data) = 0;
      virtual void OnCreateSymbolTexturedCircleMessage(const sbio::ig::symbol::SCreateSymbolTexturedCircleMessage& data) = 0;
      virtual void OnUpdateSymbolTexturedCircleMessage(const sbio::ig::symbol::SUpdateSymbolTexturedCircleMessage& data) = 0;
      virtual void OnUpdateTexturedCircleMessage(const sbio::ig::symbol::SUpdateTexturedCircleMessage& data) = 0;
      virtual void OnCreateSymbolPolygonMessage(const sbio::ig::symbol::SCreateSymbolPolygonMessage& data) = 0;
      virtual void OnUpdateSymbolPolygonMessage(const sbio::ig::symbol::SUpdateSymbolPolygonMessage& data) = 0;
      virtual void OnSetSymbolPolygonVertexMessage(const sbio::ig::symbol::SSetSymbolPolygonVertexMessage& data) = 0;
      virtual void OnCreateSymbolTexturedPolygonMessage(const sbio::ig::symbol::SCreateSymbolTexturedPolygonMessage& data) = 0;
      virtual void OnUpdateSymbolTexturedPolygonMessage(const sbio::ig::symbol::SUpdateSymbolTexturedPolygonMessage& data) = 0;
      virtual void OnSetSymbolTexturedPolygonVertexMessage(const sbio::ig::symbol::SSetSymbolTexturedPolygonVertexMessage& data) = 0;
      virtual void OnUpdateEntityBillboardSymbolSurfaceMessage(const sbio::ig::symbol::SUpdateEntityBillboardSymbolSurfaceMessage& data) = 0;
      virtual void OnCreateSymbolSurfaceMessage(const sbio::ig::symbol::SCreateSymbolSurfaceMessage& data) = 0;
      virtual void OnDestroySymbolSurfaceMessage(const sbio::ig::symbol::SDestroySymbolSurfaceMessage& data) = 0;
      virtual void OnUpdateSymbolSurfaceMessage(const sbio::ig::symbol::SUpdateSymbolSurfaceMessage& data) = 0;
      virtual void OnUpdateViewSymbolSurfaceMessage(const sbio::ig::symbol::SUpdateViewSymbolSurfaceMessage& data) = 0;
      virtual void OnSetSymbolVisibleMessage(const sbio::ig::symbol::SSetSymbolVisibleMessage& data) = 0;
      virtual void OnSetSymbolAttachedMessage(const sbio::ig::symbol::SSetSymbolAttachedMessage& data) = 0;
      virtual void OnSetSymbolUnattachedMessage(const sbio::ig::symbol::SSetSymbolUnattachedMessage& data) = 0;
      virtual void OnSetSymbolSurfaceMessage(const sbio::ig::symbol::SSetSymbolSurfaceMessage& data) = 0;
      virtual void OnSetTopLevelSymbolTransformMessage(const sbio::ig::symbol::SSetTopLevelSymbolTransformMessage& data) = 0;
      virtual void OnSetChildSymbolTransformMessage(const sbio::ig::symbol::SSetChildSymbolTransformMessage& data) = 0;
      virtual void OnUpdateSymbolMessage(const sbio::ig::symbol::SUpdateSymbolMessage& data) = 0;
      virtual void OnSetSymbolComponentStateMessage(const sbio::ig::symbol::SSetSymbolComponentStateMessage& data) = 0;
      virtual void OnSetSymbolSurfaceComponentStateMessage(const sbio::ig::symbol::SSetSymbolSurfaceComponentStateMessage& data) = 0;
      virtual void OnCreateSymbolFromTemplateMessage(const sbio::ig::symbol::SCreateSymbolFromTemplateMessage& data) = 0;
      virtual void OnUpdateCelestialSphereMessage(const sbio::ig::celestial::SUpdateCelestialSphereMessage& data) = 0;
      virtual void OnUpdateDateTimeMessage(const sbio::ig::celestial::SUpdateDateTimeMessage& data) = 0;
      virtual void OnSetCelestialSphereComponentStateMessage(const sbio::ig::celestial::SSetCelestialSphereComponentStateMessage& data) = 0;
      virtual void OnUpdateSensorMessage(const sbio::ig::sensor::SUpdateSensorMessage& data) = 0;
      virtual void OnUpdateSensorComponentMessage(const sbio::ig::sensor::SUpdateSensorComponentMessage& data) = 0;
      virtual void OnCreateMotionTrackerViewMessage(const sbio::ig::sensor::SCreateMotionTrackerViewMessage& data) = 0;
      virtual void OnCreateMotionTrackerViewGroupMessage(const sbio::ig::sensor::SCreateMotionTrackerViewGroupMessage& data) = 0;
      virtual void OnSetMotionTrackerMessage(const sbio::ig::sensor::SSetMotionTrackerMessage& data) = 0;
      virtual void OnSetAtmosphereEnabledMessage(const sbio::ig::atmosphere::SSetAtmosphereEnabledMessage& data) = 0;
      virtual void OnSetAtmosphereMessage(const sbio::ig::atmosphere::SSetAtmosphereMessage& data) = 0;
      virtual void OnSetWeatherMessage(const sbio::ig::atmosphere::SSetWeatherMessage& data) = 0;
      virtual void OnSetRegionalLayeredWeatherComponentStateMessage(const sbio::ig::atmosphere::SSetRegionalLayeredWeatherComponentStateMessage& data) = 0;
      virtual void OnSetGlobalLayeredWeatherComponentStateMessage(const sbio::ig::atmosphere::SSetGlobalLayeredWeatherComponentStateMessage& data) = 0;
      virtual void OnSetAtmosphereComponentStateMessage(const sbio::ig::atmosphere::SSetAtmosphereComponentStateMessage& data) = 0;
      virtual void OnSetMaritimeSurfaceConditionsMessage(const sbio::ig::ocean::SSetMaritimeSurfaceConditionsMessage& data) = 0;
      virtual void OnSetRegionMaritimeComponentStateMessage(const sbio::ig::ocean::SSetRegionMaritimeComponentStateMessage& data) = 0;
      virtual void OnSetGlobalMaritimeComponentStateMessage(const sbio::ig::ocean::SSetGlobalMaritimeComponentStateMessage& data) = 0;
      virtual void OnSetEarthReferenceModelMessage(const sbio::ig::earth::SSetEarthReferenceModelMessage& data) = 0;
      virtual void OnSetEventComponentStateMessage(const sbio::ig::system::SSetEventComponentStateMessage& data) = 0;
      virtual void OnSetSystemComponentStateMessage(const sbio::ig::system::SSetSystemComponentStateMessage& data) = 0;
      virtual void OnSetHostConnectedMessage(const sbio::ig::network::SHostConnectedMessage& data) {};
      virtual void OnSetHostDisconnectedMessage(const sbio::ig::network::SHostDisconnectedMessage& data) {};
    };
  }
}

#endif//#ifndef SIMBLOCKS_I_IMAGE_GENERATOR_EVENT_MESSENGER_H

//The source code in this file is licensed under the MIT License. See the LICENSE text file for full terms.
//Refer all inquiries to sales@simblocks.io
//Copyright SimBlocks LLC 2016-2026
