//Copyright SimBlocks LLC 2016-2026
/**
 * @file ImageGeneratorMessages.h
 * @brief Generated message payload types exchanged between engine systems and image-generator event handlers.
 *
 * This header defines the strongly typed message structures used by the image-generator messaging layer.
 * The types are grouped by domain such as entity, terrain, physics, view, animation, symbol, atmosphere,
 * and system messaging. Most messages are passive data containers paired with `operator<<` helpers for
 * diagnostics and logging.
 *
 * @see sbio::ig::IImageGeneratorEventHandler
 * @see sbio::ig::CImageGeneratorEventMessenger
 */
//This file has been generated by idlgen.exe. Do not modify this file directly!
#ifndef SIMBLOCKS_IMAGE_GENERATOR_MESSAGES_H
#define SIMBLOCKS_IMAGE_GENERATOR_MESSAGES_H

#include "MathLib/MathTypes.h"
#include "SymbolLib/SymbolTypes.h"
#include "CigiLib/CigiTypes.h"
#include <string>
#include <vector>

namespace sbio
{
  namespace ig
  {
    /**
     * @brief Namespace containing generated image-generator message payloads.
     *
     * Types in this namespace are intended to be passed between engine subsystems and implementations of
     * the image-generator event handling interfaces.
     */

    /**
     * @brief Stores a north-east-down basis expressed in geocentric coordinates.
     *
     * This helper value type is used by messages that provide a full top-level orientation as explicit basis
     * vectors instead of Euler angles.
     */
    struct NEDRotation
    {
      sbio::math::GeocentricCoordinates North;
      sbio::math::GeocentricCoordinates East;
      sbio::math::GeocentricCoordinates Down;
    };

    inline std::ostream& operator<<(std::ostream& s, const NEDRotation& rhs)
    {
      s << "North: \n" << rhs.North << std::endl;
      s << "East: \n" << rhs.East << std::endl;
      s << "Down: \n" << rhs.Down << std::endl;
      return s;
    }

    inline std::ostream& operator<<(std::ostream& s, const sbio::math::TBodyEulerRotation& rhs)
    {
      s << "Roll: " << rhs.roll << std::endl;
      s << "Pitch: " << rhs.pitch << std::endl;
      s << "Yaw: " << rhs.yaw << std::endl;
      return s;
    }

    /**
     * @brief Stores a reduced body-frame orientation using forward and up vectors.
     *
     * The remaining orthogonal axis can be derived by consumers when needed.
     */
    struct BodyRotation
    {
      sbio::math::BodyCoordinates Forward;
      sbio::math::BodyCoordinates Up;
    };

    inline std::ostream& operator<<(std::ostream& s, const BodyRotation& rhs)
    {
      s << "Forward: \n" << rhs.Forward[0] << ", " << rhs.Forward[1] << ", " << rhs.Forward[2] << std::endl;
      s << "Up: \n" << rhs.Up[0] << ", " << rhs.Up[1] << ", " << rhs.Up[2] << std::endl;
      return s;
    }

    /**
     * @brief Carries component payload words associated with a component state update.
     *
     * The interpretation of each field depends on the specific CIGI component being addressed.
     */
    struct SComponentData
    {
      uint32_t ComponentData0 = {0};
      uint32_t ComponentData1 = {0};
      uint32_t ComponentData2 = {0};
      uint32_t ComponentData3 = {0};
      uint32_t ComponentData4 = {0};
      uint32_t ComponentData5 = {0};
    };

    inline std::ostream& operator<<(std::ostream& s, const SComponentData& rhs)
    {
      s << "ComponentData0: " << std::to_string(rhs.ComponentData0) << std::endl;
      s << "ComponentData1: " << std::to_string(rhs.ComponentData1) << std::endl;
      s << "ComponentData2: " << std::to_string(rhs.ComponentData2) << std::endl;
      s << "ComponentData3: " << std::to_string(rhs.ComponentData3) << std::endl;
      s << "ComponentData4: " << std::to_string(rhs.ComponentData4) << std::endl;
      s << "ComponentData5: " << std::to_string(rhs.ComponentData5) << std::endl;
      return s;
    }

    namespace entity
    {
      /**
       * @brief Entity lifecycle and transform update messages.
       */

      struct SCreateEntityMessage
      {
        sbio::EntityID EntityID = sbio::UnknownEntityID;
        sbio::entity::SEntityType EntityType;
        sbio::ShortEntityTypeID ShortEntityTypeID = sbio::UnknownShortEntityTypeID;
      };

      inline std::ostream& operator<<(std::ostream& s, const SCreateEntityMessage& rhs)
      {
        s << "EntityID: " << rhs.EntityID << std::endl;
        s << "EntityType: \n" << rhs.EntityType.ToEnumerationString() << std::endl;
        s << "ShortEntityTypeID: " << rhs.ShortEntityTypeID << std::endl;
        return s;
      }

      struct SDestroyEntityMessage
      {
        sbio::EntityID EntityID = sbio::UnknownEntityID;
      };

      inline std::ostream& operator<<(std::ostream& s, const SDestroyEntityMessage& rhs)
      {
        s << "EntityID: " << rhs.EntityID << std::endl;
        return s;
      }

      struct SUpdateTopLevelEntityTransformMessage
      {
        sbio::EntityID EntityID = sbio::UnknownEntityID;
        sbio::math::SGeodeticCoordinates Coordinate;
        NEDRotation Rotation;
        sbio::math::TBodyEulerRotation EulerRotation;
        uint16_t Clamp = {0};
      };

      inline std::ostream& operator<<(std::ostream& s, sbio::math::SGeodeticCoordinates& rhs)
      {
        s << "Latitude: " << rhs.latitude << std::endl;
        s << "Longitude: " << rhs.longitude << std::endl;
        s << "Altitude: " << rhs.altitude << std::endl;
        return s;
      }

      inline std::ostream& operator<<(std::ostream& s, const SUpdateTopLevelEntityTransformMessage& rhs)
      {
        s << "EntityID: " << rhs.EntityID << std::endl;
        s << "Coordinate: \n" << rhs.Coordinate.latitude << ", " << rhs.Coordinate.longitude << ", " << rhs.Coordinate.altitude << std::endl;
        s << "Rotation: \n" << rhs.Rotation << std::endl;
        s << "EulerRotation: \n" << rhs.EulerRotation.yaw << ", " << rhs.EulerRotation.pitch << ", " << rhs.EulerRotation.roll << std::endl;
        s << "Clamp: " << std::to_string(rhs.Clamp) << std::endl;
        return s;
      }

      struct SUpdateChildEntityTransformMessage
      {
        sbio::EntityID EntityID = sbio::UnknownEntityID;
        sbio::math::BodyCoordinates Offset;
        BodyRotation Rotation;
      };

      inline std::ostream& operator<<(std::ostream& s, const SUpdateChildEntityTransformMessage& rhs)
      {
        s << "EntityID: " << rhs.EntityID << std::endl;
        s << "Offset: \n" << rhs.Offset[0] << ", " << rhs.Offset[1] << ", " << rhs.Offset[2] << std::endl;
        s << "Rotation: \n" << rhs.Rotation << std::endl;
        return s;
      }

      struct SSetEntityAttachedMessage
      {
        sbio::EntityID EntityID = sbio::UnknownEntityID;
        sbio::EntityID ParentID = sbio::UnknownEntityID;
      };

      inline std::ostream& operator<<(std::ostream& s, const SSetEntityAttachedMessage& rhs)
      {
        s << "EntityID: " << rhs.EntityID << std::endl;
        s << "ParentID: " << rhs.ParentID << std::endl;
        return s;
      }

      struct SSetEntityActiveMessage
      {
        sbio::EntityID EntityID = sbio::UnknownEntityID;
        bool isActive = false;
      };

      inline std::ostream& operator<<(std::ostream& s, const SSetEntityActiveMessage& rhs)
      {
        s << "EntityID: " << rhs.EntityID << std::endl;
        s << "isActive: " << std::to_string(rhs.isActive) << std::endl;
        return s;
      }

      struct SSetEntityUnattachedMessage
      {
        sbio::EntityID EntityID = sbio::UnknownEntityID;
      };

      inline std::ostream& operator<<(std::ostream& s, const SSetEntityUnattachedMessage& rhs)
      {
        s << "EntityID: " << rhs.EntityID << std::endl;
        return s;
      }

      struct SSetEntityComponentStateMessage
      {
        sbio::EntityID EntityID = sbio::UnknownEntityID;
        sbio::cigi::CigiComponentID ComponentID = sbio::cigi::UnknownCigiComponentID;
        int32_t ComponentState = {0};
        SComponentData ComponentData;
      };

      inline std::ostream& operator<<(std::ostream& s, const SSetEntityComponentStateMessage& rhs)
      {
        s << "EntityID: " << rhs.EntityID << std::endl;
        s << "ComponentID: " << rhs.ComponentID << std::endl;
        s << "ComponentState: " << std::to_string(rhs.ComponentState) << std::endl;
        s << "ComponentData: \n" << rhs.ComponentData << std::endl;
        return s;
      }

      struct SUpdateArticulatedPartTransformMessage
      {
        sbio::EntityID EntityID = sbio::UnknownEntityID;
        sbio::ArticulatedPartID ArticulatedPartID = sbio::UnknownArticulatedPartID;
        sbio::math::BodyCoordinates Offset;
        BodyRotation Rotation;
      };

      inline std::ostream& operator<<(std::ostream& s, const SUpdateArticulatedPartTransformMessage& rhs)
      {
        s << "EntityID: " << rhs.EntityID << std::endl;
        s << "ArticulationID: " << rhs.ArticulatedPartID << std::endl;
        s << "Offset: \n" << rhs.Offset[0] << ", " << rhs.Offset[1] << ", " << rhs.Offset[2] << std::endl;
        s << "Rotation: \n" << rhs.Rotation << std::endl;
        return s;
      }

      struct SSetArticulatedPartVisibleMessage
      {
        sbio::EntityID EntityID = sbio::UnknownEntityID;
        sbio::ArticulatedPartID ArticulatedPartID = sbio::UnknownArticulatedPartID;
        bool Visible = false;
      };

      inline std::ostream& operator<<(std::ostream& s, const SSetArticulatedPartVisibleMessage& rhs)
      {
        s << "EntityID: " << rhs.EntityID << std::endl;
        s << "ArticulationID: " << rhs.ArticulatedPartID << std::endl;
        s << "Visible: " << std::to_string(rhs.Visible) << std::endl;
        return s;
      }

      struct SSetEntityAlphaMessage
      {
        sbio::EntityID EntityID = sbio::UnknownEntityID;
        float Alpha = {0};
      };

      inline std::ostream& operator<<(std::ostream& s, const SSetEntityAlphaMessage& rhs)
      {
        s << "EntityID: " << rhs.EntityID << std::endl;
        s << "Alpha: " << std::to_string(rhs.Alpha) << std::endl;
        return s;
      }

      struct SSetEntityCollisionDetectionEnabledMessage
      {
        sbio::EntityID EntityID = sbio::UnknownEntityID;
        bool Enabled = false;
      };

      inline std::ostream& operator<<(std::ostream& s, const SSetEntityCollisionDetectionEnabledMessage& rhs)
      {
        s << "EntityID: " << rhs.EntityID << std::endl;
        s << "Enabled: " << std::to_string(rhs.Enabled) << std::endl;
        return s;
      }
    }

    namespace terrain
    {
      /**
       * @brief Terrain queries, line-of-sight requests, and terrain component updates.
       */

      /**
       * @brief Common payload shared by line-of-sight segment and vector request messages.
       *
       * The request identifies the query, the start and end points in geocentric coordinates, and optional
       * filtering information used by the terrain or scene intersection implementation.
       */
      struct SBaseLineOfSightRequestMessage
      {
        LineOfSightRequestID LosID = sbio::UnknownLineOfSightRequestID;
        sbio::math::GeocentricCoordinates Start;
        sbio::math::GeocentricCoordinates End;
        float AlphaThreshold = {0};
        uint32_t MaterialMask = {0};
      };

      struct SLineOfSightSegmentRequestBasicMessage : SBaseLineOfSightRequestMessage
      {
      };

      /**
       * @brief Extended line-of-sight segment request that specifies the desired response coordinate system.
       */
      struct SLineOfSightSegmentRequestExtendedMessage : SBaseLineOfSightRequestMessage
      {
        ETopLevelCoordinateSystem eResponseCoordinateSystem = ETopLevelCoordinateSystem::UNKNOWN;
      };

      struct SLineOfSightVectorRequestBasicMessage : SBaseLineOfSightRequestMessage
      {
      };

      /**
       * @brief Extended line-of-sight vector request that specifies the desired response coordinate system.
       */
      struct SLineOfSightVectorRequestExtendedMessage : SBaseLineOfSightRequestMessage
      {
        ETopLevelCoordinateSystem eResponseCoordinateSystem = ETopLevelCoordinateSystem::UNKNOWN;
      };

      inline std::ostream& operator<<(std::ostream& s, const SBaseLineOfSightRequestMessage& rhs)
      {
        s << "LosID: " << rhs.LosID.Value() << std::endl;
        s << "Start: \n" << rhs.Start << std::endl;
        s << "End: \n" << rhs.End << std::endl;
        s << "AlphaThreshold: " << std::to_string(rhs.AlphaThreshold) << std::endl;
        s << "MaterialMask: " << std::to_string(rhs.MaterialMask) << std::endl;
        return s;
      }

      /**
       * @brief Basic line-of-sight response containing hit validity, visibility, and range information.
       */
      struct SLineOfSightResponseMessage
      {
        uint16_t LosID = {0};
        sbio::EntityID EntityID = sbio::UnknownEntityID;
        bool isValid = false;
        bool isEntityIDValid = false;
        bool isVisible = false;
        uint8_t ResponseCount = {0};
        double Range = {0};
      };

      inline std::ostream& operator<<(std::ostream& s, const SLineOfSightResponseMessage& rhs)
      {
        s << "LosID: " << std::to_string(rhs.LosID) << std::endl;
        s << "EntityID: " << rhs.EntityID << std::endl;
        s << "isValid: " << std::to_string(rhs.isValid) << std::endl;
        s << "isEntityIDValid: " << std::to_string(rhs.isEntityIDValid) << std::endl;
        s << "isVisible: " << std::to_string(rhs.isVisible) << std::endl;
        s << "ResponseCount: " << std::to_string(rhs.ResponseCount) << std::endl;
        s << "Range: " << std::to_string(rhs.Range) << std::endl;
        return s;
      }

      /**
       * @brief Extended line-of-sight response including surface hit details.
       */
      struct SLineOfSightExtendedResponseMessage
      {
        uint16_t LosID = {0};
        sbio::EntityID EntityID = sbio::UnknownEntityID;
        bool isValid = false;
        bool isEntityIDValid = false;
        bool isVisible = false;
        uint8_t ResponseCount = {0};
        double Range = {0};
        sbio::math::GeocentricCoordinates HitLocation;
        sbio::SColor4f HitColor;
        sbio::MaterialID MaterialCode = sbio::UnknownMaterialID;
        sbio::math::BodyCoordinates Normal;
      };

      inline std::ostream& operator<<(std::ostream& s, const SLineOfSightExtendedResponseMessage& rhs)
      {
        s << "LosID: " << std::to_string(rhs.LosID) << std::endl;
        s << "EntityID: " << rhs.EntityID << std::endl;
        s << "isValid: " << std::to_string(rhs.isValid) << std::endl;
        s << "isEntityIDValid: " << std::to_string(rhs.isEntityIDValid) << std::endl;
        s << "isVisible: " << std::to_string(rhs.isVisible) << std::endl;
        s << "ResponseCount: " << std::to_string(rhs.ResponseCount) << std::endl;
        s << "Range: " << std::to_string(rhs.Range) << std::endl;
        s << "HitLocation: \n" << rhs.HitLocation << std::endl;
        s << "HitColor: \n" << rhs.HitColor.r << ", " << rhs.HitColor.g << ", " << rhs.HitColor.b << ", " << rhs.HitColor.a << std::endl;
        s << "MaterialCode: " << rhs.MaterialCode << std::endl;
        s << "Normal: \n" << rhs.Normal[0] << ", " << rhs.Normal[1] << ", " << rhs.Normal[2] << std::endl;
        return s;
      }

      /**
       * @brief Requests height-above-terrain evaluation at a geodetic point.
       */
      struct SHeightAboveTerrainRequestMessage
      {
        sbio::HATHOTID HatHotID = sbio::UnknownHATHOTID;
        sbio::math::SGeodeticCoordinates Point;
        bool isExtendedRequest = false;
      };

      /**
       * @brief Requests terrain elevation at a geodetic point.
       */
      struct SHeightOfTerrainRequestMessage
      {
        sbio::HATHOTID HatHotID = sbio::UnknownHATHOTID;
        sbio::math::SGeodeticCoordinates Point;
        bool isExtendedRequest = false;
      };

      inline std::ostream& operator<<(std::ostream& s, const SHeightOfTerrainRequestMessage& rhs)
      {
        s << "HatHotID: " << rhs.HatHotID << std::endl;
        s << "Point: \n";
        s << "Lat=" << rhs.Point.latitude.Value() << ", Lon=" << rhs.Point.longitude.Value() << ", Alt=" << rhs.Point.altitude << std::endl;
        s << "isExtendedRequest: " << std::to_string(rhs.isExtendedRequest) << std::endl;
        return s;
      }

      /**
       * @brief Returns height-above-terrain results in meters relative to the terrain surface.
       */
      struct SHeightAboveTerrainResponseMessage
      {
        sbio::HATHOTID HatHotID = sbio::UnknownHATHOTID;
        bool isValid = false;
        double Height = {0};//height relative to the terrain, in meters
      };

      /**
       * @brief Returns terrain elevation relative to the WGS84 ellipsoid.
       */
      struct SHeightOfTerrainResponseMessage
      {
        sbio::HATHOTID HatHotID = sbio::UnknownHATHOTID;
        bool isValid = false;
        sbio::math::HeightRelativeToWGS84Ellipsoid Height = sbio::math::HeightRelativeToWGS84Ellipsoid(0);
      };

      inline std::ostream& operator<<(std::ostream& s, const SHeightOfTerrainResponseMessage& rhs)
      {
        s << "HatHotID: " << rhs.HatHotID << std::endl;
        s << "isValid: " << std::to_string(rhs.isValid) << std::endl;
        s << "Height: \n" << rhs.Height << std::endl;
        return s;
      }

      /**
       * @brief Extended terrain-height response that includes hit location, material, and surface normal.
       */
      struct SHeightOfTerrainExtendedResponseMessage
      {
        sbio::HATHOTID HatHotID = sbio::UnknownHATHOTID;
        bool isValid = false;
        sbio::math::GeocentricCoordinates IntersectionPoint;
        sbio::MaterialID MaterialCode = sbio::UnknownMaterialID;
        sbio::math::BodyCoordinates Normal;
      };

      inline std::ostream& operator<<(std::ostream& s, const SHeightOfTerrainExtendedResponseMessage& rhs)
      {
        s << "HatHotID: " << rhs.HatHotID << std::endl;
        s << "isValid: " << std::to_string(rhs.isValid) << std::endl;
        s << "IntersectionPoint: \n" << rhs.IntersectionPoint << std::endl;
        s << "MaterialCode: " << rhs.MaterialCode << std::endl;
        s << "Normal: \n" << rhs.Normal[0] << ", " << rhs.Normal[1] << ", " << rhs.Normal[2] << std::endl;
        return s;
      }

      struct SSetRegionalTerrainSurfaceComponentStateMessage
      {
        sbio::RegionalTerrainSurfaceID RegionalTerrainSurfaceID = sbio::UnknownRegionalTerrainSurfaceID;
        sbio::cigi::CigiComponentID ComponentID = sbio::cigi::UnknownCigiComponentID;
        int32_t ComponentState = {0};
        SComponentData ComponentData;
      };

      inline std::ostream& operator<<(std::ostream& s, const SSetRegionalTerrainSurfaceComponentStateMessage& rhs)
      {
        s << "RegionalTerrainSurfaceID: " << rhs.RegionalTerrainSurfaceID << std::endl;
        s << "ComponentID: " << rhs.ComponentID << std::endl;
        s << "ComponentState: " << std::to_string(rhs.ComponentState) << std::endl;
        s << "ComponentData: \n" << rhs.ComponentData << std::endl;
        return s;
      }

      struct SSetGlobalTerrainComponentStateMessage
      {
        sbio::GlobalTerrainSurfaceID GlobalTerrainSurfaceID = sbio::UnknownGlobalTerrainSurfaceID;
        sbio::cigi::CigiComponentID ComponentID = sbio::cigi::UnknownCigiComponentID;
        int32_t ComponentState = {0};
        SComponentData ComponentData;
      };

      inline std::ostream& operator<<(std::ostream& s, const SSetGlobalTerrainComponentStateMessage& rhs)
      {
        s << "GlobalTerrainSurfaceID: " << rhs.GlobalTerrainSurfaceID << std::endl;
        s << "ComponentID: " << rhs.ComponentID << std::endl;
        s << "ComponentState: " << std::to_string(rhs.ComponentState) << std::endl;
        s << "ComponentData: \n" << rhs.ComponentData << std::endl;
        return s;
      }
    }

    namespace physics
    {
      /**
       * @brief Collision segment and collision volume control and notification messages.
       */

      struct SSetCollisionDetectionSegmentEnabledMessage
      {
        sbio::SegmentID SegmentID = sbio::UnknownSegmentID;
        sbio::EntityID EntityID = sbio::UnknownEntityID;
        bool Enabled = false;
      };

      inline std::ostream& operator<<(std::ostream& s, const SSetCollisionDetectionSegmentEnabledMessage& rhs)
      {
        s << "SegmentID: " << rhs.SegmentID << std::endl;
        s << "EntityID: " << rhs.EntityID << std::endl;
        s << "Enabled: " << std::to_string(rhs.Enabled) << std::endl;
        return s;
      }

      struct SSetCollisionDetectionSegmentMessage
      {
        sbio::SegmentID SegmentID = sbio::UnknownSegmentID;
        sbio::EntityID EntityID = sbio::UnknownEntityID;
        sbio::math::BodyCoordinates BeginPos;
        sbio::math::BodyCoordinates EndPos;
        uint32_t MaterialMask = {0};
      };

      inline std::ostream& operator<<(std::ostream& s, const SSetCollisionDetectionSegmentMessage& rhs)
      {
        s << "SegmentID: " << rhs.SegmentID << std::endl;
        s << "EntityID: " << rhs.EntityID << std::endl;
        s << "BeginPos: \n" << rhs.BeginPos[0] << ", " << rhs.BeginPos[1] << ", " << rhs.BeginPos[2] << std::endl;
        s << "EndPos: \n" << rhs.EndPos[0] << ", " << rhs.EndPos[1] << ", " << rhs.EndPos[2] << std::endl;
        s << "MaterialMask: " << std::to_string(rhs.MaterialMask) << std::endl;
        return s;
      }

      struct SCreateCollisionDetectionSegmentMessage
      {
        sbio::SegmentID SegmentID = sbio::UnknownSegmentID;
        sbio::EntityID EntityID = sbio::UnknownEntityID;
      };

      inline std::ostream& operator<<(std::ostream& s, const SCreateCollisionDetectionSegmentMessage& rhs)
      {
        s << "SegmentID: " << rhs.SegmentID << std::endl;
        s << "EntityID: " << rhs.EntityID << std::endl;
        return s;
      }

      struct SCreateCollisionVolumeSphereMessage
      {
        sbio::EntityID EntityID = sbio::UnknownEntityID;
        sbio::VolumeID VolumeID = sbio::UnknownVolumeID;
      };

      inline std::ostream& operator<<(std::ostream& s, const SCreateCollisionVolumeSphereMessage& rhs)
      {
        s << "EntityID: " << rhs.EntityID << std::endl;
        s << "VolumeID: " << rhs.VolumeID << std::endl;
        return s;
      }

      struct SCreateCollisionVolumeCuboidMessage
      {
        sbio::EntityID EntityID = sbio::UnknownEntityID;
        sbio::VolumeID VolumeID = sbio::UnknownVolumeID;
      };

      inline std::ostream& operator<<(std::ostream& s, const SCreateCollisionVolumeCuboidMessage& rhs)
      {
        s << "EntityID: " << rhs.EntityID << std::endl;
        s << "VolumeID: " << rhs.VolumeID << std::endl;
        return s;
      }

      struct SSetCollisionVolumeEnabledMessage
      {
        sbio::EntityID EntityID = sbio::UnknownEntityID;
        sbio::VolumeID VolumeID = sbio::UnknownVolumeID;
        bool Enabled = false;
      };

      inline std::ostream& operator<<(std::ostream& s, const SSetCollisionVolumeEnabledMessage& rhs)
      {
        s << "EntityID: " << rhs.EntityID << std::endl;
        s << "VolumeID: " << rhs.VolumeID << std::endl;
        s << "Enabled: " << std::to_string(rhs.Enabled) << std::endl;
        return s;
      }

      struct SSetCollisionVolumeMessage
      {
        sbio::EntityID EntityID = sbio::UnknownEntityID;
        sbio::VolumeID VolumeID = sbio::UnknownVolumeID;
        float Radius = {0};
        sbio::math::BodyCoordinates Offset;
        float Height = {0};
        float Width = {0};
        float Depth = {0};
        BodyRotation Rotation;
      };

      inline std::ostream& operator<<(std::ostream& s, const SSetCollisionVolumeMessage& rhs)
      {
        s << "EntityID: " << rhs.EntityID << std::endl;
        s << "VolumeID: " << rhs.VolumeID << std::endl;
        s << "Radius: " << std::to_string(rhs.Radius) << std::endl;
        s << "Offset: \n" << rhs.Offset[0] << ", " << rhs.Offset[1] << ", " << rhs.Offset[2] << std::endl;
        s << "Height: " << std::to_string(rhs.Height) << std::endl;
        s << "Width: " << std::to_string(rhs.Width) << std::endl;
        s << "Depth: " << std::to_string(rhs.Depth) << std::endl;
        s << "Rotation: \n" << rhs.Rotation << std::endl;
        return s;
      }

      struct SDestroyCollisionVolumeMessage
      {
        sbio::EntityID EntityID = sbio::UnknownEntityID;
        sbio::VolumeID VolumeID = sbio::UnknownVolumeID;
      };

      inline std::ostream& operator<<(std::ostream& s, const SDestroyCollisionVolumeMessage& rhs)
      {
        s << "EntityID: " << rhs.EntityID << std::endl;
        s << "VolumeID: " << rhs.VolumeID << std::endl;
        return s;
      }

      struct SCollisionDetectionSegmentNotificationMessage
      {
        sbio::EntityID EntityID = sbio::UnknownEntityID;
        sbio::SegmentID SegmentID = sbio::UnknownSegmentID;
        sbio::MaterialID MaterialCode = sbio::UnknownMaterialID;
        float IntersectionDistance = {0};
      };

      inline std::ostream& operator<<(std::ostream& s, const SCollisionDetectionSegmentNotificationMessage& rhs)
      {
        s << "EntityID: " << rhs.EntityID << std::endl;
        s << "SegmentID: " << rhs.SegmentID << std::endl;
        s << "MaterialCode: " << rhs.MaterialCode << std::endl;
        s << "IntersectionDistance: " << std::to_string(rhs.IntersectionDistance) << std::endl;
        return s;
      }

      struct SCollisionDetectionSegmentEntityNotificationMessage
      {
        sbio::EntityID EntityID = sbio::UnknownEntityID;
        sbio::EntityID ContactedEntityID = sbio::UnknownEntityID;
        sbio::SegmentID SegmentID = sbio::UnknownSegmentID;
        sbio::MaterialID MaterialCode = sbio::UnknownMaterialID;
        float IntersectionDistance = {0};
      };

      inline std::ostream& operator<<(std::ostream& s, const SCollisionDetectionSegmentEntityNotificationMessage& rhs)
      {
        s << "EntityID: " << rhs.EntityID << std::endl;
        s << "ContactedEntityID: " << rhs.ContactedEntityID << std::endl;
        s << "SegmentID: " << rhs.SegmentID << std::endl;
        s << "MaterialCode: " << rhs.MaterialCode << std::endl;
        s << "IntersectionDistance: " << std::to_string(rhs.IntersectionDistance) << std::endl;
        return s;
      }

      struct SCollisionDetectionVolumeNotificationMessage
      {
        sbio::VolumeID VolumeID = sbio::UnknownVolumeID;
        sbio::EntityID EntityID = sbio::UnknownEntityID;
        sbio::VolumeID ContactedVolumeID = sbio::UnknownVolumeID;
      };

      inline std::ostream& operator<<(std::ostream& s, const SCollisionDetectionVolumeNotificationMessage& rhs)
      {
        s << "VolumeID: " << rhs.VolumeID << std::endl;
        s << "EntityID: " << rhs.EntityID << std::endl;
        s << "ContactedVolumeID: " << rhs.ContactedVolumeID << std::endl;
        return s;
      }

      struct SCollisionDetectionVolumeEntityNotificationMessage
      {
        sbio::VolumeID VolumeID = sbio::UnknownVolumeID;
        sbio::EntityID EntityID = sbio::UnknownEntityID;
        sbio::VolumeID ContactedVolumeID = sbio::UnknownVolumeID;
        sbio::EntityID ContactedEntityID = sbio::UnknownEntityID;
      };

      inline std::ostream& operator<<(std::ostream& s, const SCollisionDetectionVolumeEntityNotificationMessage& rhs)
      {
        s << "VolumeID: " << rhs.VolumeID << std::endl;
        s << "EntityID: " << rhs.EntityID << std::endl;
        s << "ContactedVolumeID: " << rhs.ContactedVolumeID << std::endl;
        s << "ContactedEntityID: " << rhs.ContactedEntityID << std::endl;
        return s;
      }
    }

    namespace view
    {
      /**
       * @brief Camera, projection, view, and view-group update messages.
       */

      struct SUpdateAttachedCameraTransformMessage
      {
        sbio::ViewID ViewID = sbio::UnknownViewID;
        sbio::math::BodyCoordinates Offset;
        BodyRotation Rotation;
      };

      inline std::ostream& operator<<(std::ostream& s, const SUpdateAttachedCameraTransformMessage& rhs)
      {
        s << "CameraID: " << rhs.ViewID << std::endl;
        s << "Offset: \n" << rhs.Offset[0] << ", " << rhs.Offset[1] << ", " << rhs.Offset[2] << std::endl;
        s << "Rotation: \n" << rhs.Rotation << std::endl;
        return s;
      }

      struct SSetCameraAttachedToEntityMessage
      {
        sbio::ViewID ViewID = sbio::UnknownViewID;
        sbio::EntityID EntityID = sbio::UnknownEntityID;
      };

      inline std::ostream& operator<<(std::ostream& s, const SSetCameraAttachedToEntityMessage& rhs)
      {
        s << "CameraID: " << rhs.ViewID << std::endl;
        s << "EntityID: " << rhs.EntityID << std::endl;
        return s;
      }

      struct SSetCameraUnattachedMessage
      {
        sbio::ViewID ViewID = sbio::UnknownViewID;
      };

      inline std::ostream& operator<<(std::ostream& s, const SSetCameraUnattachedMessage& rhs)
      {
        s << "CameraID: " << rhs.ViewID << std::endl;
        return s;
      }

      struct SSetCameraProjectionMessage
      {
        sbio::ViewID ViewID = sbio::UnknownViewID;
        float Near = {0};
        float Far = {0};
        float LeftHalfAngle = {0};
        float RightHalfAngle = {0};
        float TopHalfAngle = {0};
        float BottomHalfAngle = {0};
        EProjectionMode ProjectionMode = EProjectionMode::UNKNOWN;
        EMirrorMode MirrorMode = EMirrorMode::UNKNOWN;
      };

      inline std::ostream& operator<<(std::ostream& s, const SSetCameraProjectionMessage& rhs)
      {
        s << "CameraID: " << rhs.ViewID << std::endl;
        s << "Near: " << std::to_string(rhs.Near) << std::endl;
        s << "Far: " << std::to_string(rhs.Far) << std::endl;
        s << "LeftHalfAngle: " << std::to_string(rhs.LeftHalfAngle) << std::endl;
        s << "RightHalfAngle: " << std::to_string(rhs.RightHalfAngle) << std::endl;
        s << "TopHalfAngle: " << std::to_string(rhs.TopHalfAngle) << std::endl;
        s << "BottomHalfAngle: " << std::to_string(rhs.BottomHalfAngle) << std::endl;
        s << "ProjectionMode: \n" << (int)rhs.ProjectionMode << std::endl;
        s << "MirrorMode: \n" << (int)rhs.MirrorMode << std::endl;
        return s;
      }

      struct SSetViewComponentStateMessage
      {
        sbio::ViewID ViewID = sbio::UnknownViewID;
        sbio::cigi::CigiComponentID ComponentID = sbio::cigi::UnknownCigiComponentID;
        int32_t ComponentState = {0};
        SComponentData ComponentData;
      };

      inline std::ostream& operator<<(std::ostream& s, const SSetViewComponentStateMessage& rhs)
      {
        s << "ViewID: " << rhs.ViewID << std::endl;
        s << "ComponentID: " << rhs.ComponentID << std::endl;
        s << "ComponentState: " << std::to_string(rhs.ComponentState) << std::endl;
        s << "ComponentData: \n" << rhs.ComponentData << std::endl;
        return s;
      }

      struct SSetViewGroupComponentStateMessage
      {
        sbio::ViewGroupID ViewGroupID = sbio::UnknownViewGroupID;
        sbio::cigi::CigiComponentID ComponentID = sbio::cigi::UnknownCigiComponentID;
        int32_t ComponentState = {0};
        SComponentData ComponentData;
      };

      inline std::ostream& operator<<(std::ostream& s, const SSetViewGroupComponentStateMessage& rhs)
      {
        s << "ViewGroupID: " << rhs.ViewGroupID << std::endl;
        s << "ComponentID: " << rhs.ComponentID << std::endl;
        s << "ComponentState: " << std::to_string(rhs.ComponentState) << std::endl;
        s << "ComponentData: \n" << rhs.ComponentData << std::endl;
        return s;
      }
    }

    namespace database
    {
      /**
       * @brief Database loading and unloading message payloads.
       */

      struct SLoadDatabaseMessage
      {
        sbio::DatabaseID DatabaseID = sbio::UnknownDatabaseID;
      };

      inline std::ostream& operator<<(std::ostream& s, const SLoadDatabaseMessage& rhs)
      {
        s << "DatabaseID: " << rhs.DatabaseID << std::endl;
        return s;
      }
    }

    namespace animation
    {
      /**
       * @brief Animation control messages and animation stop notifications.
       */

      struct SSetAnimationDirectionMessage
      {
        sbio::EntityID EntityID = sbio::UnknownEntityID;
        sbio::AnimationID AnimationID = sbio::UnknownAnimationID;
        bool isForward = false;
      };

      inline std::ostream& operator<<(std::ostream& s, const SSetAnimationDirectionMessage& rhs)
      {
        s << "EntityID: " << rhs.EntityID << std::endl;
        s << "AnimationID: " << rhs.AnimationID << std::endl;
        s << "isForward: " << std::to_string(rhs.isForward) << std::endl;
        return s;
      }

      struct SSetAnimationLoopModeMessage
      {
        sbio::EntityID EntityID = sbio::UnknownEntityID;
        sbio::AnimationID AnimationID = sbio::UnknownAnimationID;
        bool Continuous = false;
      };

      inline std::ostream& operator<<(std::ostream& s, const SSetAnimationLoopModeMessage& rhs)
      {
        s << "EntityID: " << rhs.EntityID << std::endl;
        s << "AnimationID: " << rhs.AnimationID << std::endl;
        s << "Continuous: " << std::to_string(rhs.Continuous) << std::endl;
        return s;
      }

      struct SSetAnimationSpeedMessage
      {
        sbio::EntityID EntityID = sbio::UnknownEntityID;
        sbio::AnimationID AnimationID = sbio::UnknownAnimationID;
        float Speed = {0};
      };

      inline std::ostream& operator<<(std::ostream& s, const SSetAnimationSpeedMessage& rhs)
      {
        s << "EntityID: " << rhs.EntityID << std::endl;
        s << "AnimationID: " << rhs.AnimationID << std::endl;
        s << "Speed: " << std::to_string(rhs.Speed) << std::endl;
        return s;
      }

      struct SStopEntityAnimationMessage
      {
        sbio::EntityID EntityID = sbio::UnknownEntityID;
        sbio::AnimationID AnimationID = sbio::UnknownAnimationID;
      };

      inline std::ostream& operator<<(std::ostream& s, const SStopEntityAnimationMessage& rhs)
      {
        s << "EntityID: " << rhs.EntityID << std::endl;
        s << "AnimationID: " << rhs.AnimationID << std::endl;
        return s;
      }

      struct SStopAtCurrentFrameEntityAnimationMessage
      {
        sbio::EntityID EntityID = sbio::UnknownEntityID;
        sbio::AnimationID AnimationID = sbio::UnknownAnimationID;
      };

      inline std::ostream& operator<<(std::ostream& s, const SStopAtCurrentFrameEntityAnimationMessage& rhs)
      {
        s << "EntityID: " << rhs.EntityID << std::endl;
        s << "AnimationID: " << rhs.AnimationID << std::endl;
        return s;
      }

      struct SPauseEntityAnimationMessage
      {
        sbio::EntityID EntityID = sbio::UnknownEntityID;
        sbio::AnimationID AnimationID = sbio::UnknownAnimationID;
      };

      inline std::ostream& operator<<(std::ostream& s, const SPauseEntityAnimationMessage& rhs)
      {
        s << "EntityID: " << rhs.EntityID << std::endl;
        s << "AnimationID: " << rhs.AnimationID << std::endl;
        return s;
      }

      struct SPlayEntityAnimationMessage
      {
        sbio::EntityID EntityID = sbio::UnknownEntityID;
        sbio::AnimationID AnimationID = sbio::UnknownAnimationID;
      };

      inline std::ostream& operator<<(std::ostream& s, const SPlayEntityAnimationMessage& rhs)
      {
        s << "EntityID: " << rhs.EntityID << std::endl;
        s << "AnimationID: " << rhs.AnimationID << std::endl;
        return s;
      }

      struct SRestartEntityAnimationMessage
      {
        sbio::EntityID EntityID = sbio::UnknownEntityID;
        sbio::AnimationID AnimationID = sbio::UnknownAnimationID;
      };

      inline std::ostream& operator<<(std::ostream& s, const SRestartEntityAnimationMessage& rhs)
      {
        s << "EntityID: " << rhs.EntityID << std::endl;
        s << "AnimationID: " << rhs.AnimationID << std::endl;
        return s;
      }

      struct SEntityAnimationStopNotificationMessage
      {
        sbio::EntityID EntityID = sbio::UnknownEntityID;
      };

      inline std::ostream& operator<<(std::ostream& s, const SEntityAnimationStopNotificationMessage& rhs)
      {
        s << "EntityID: " << rhs.EntityID << std::endl;
        return s;
      }
    }

    namespace symbol
    {
      /**
       * @brief Symbol creation, geometry, attachment, surface, and component-state messages.
       */

      struct SCreateSymbolTextMessage
      {
        sbio::symbol::SymbolID SymbolID = sbio::symbol::UnknownSymbolID;
      };

      inline std::ostream& operator<<(std::ostream& s, const SCreateSymbolTextMessage& rhs)
      {
        s << "SymbolID: " << rhs.SymbolID << std::endl;
        return s;
      }

      struct SUpdateSymbolTextMessage
      {
        sbio::symbol::SymbolID SymbolID = sbio::symbol::UnknownSymbolID;
        sbio::FontID FontID = sbio::UnknownFontID;
        float FontSize = {0};
        char Text[256] = {0};
        sbio::symbol::ETextAlignment Alignment = sbio::symbol::ETextAlignment::UNKNOWN;
        sbio::symbol::ETextOrientation Orientation = sbio::symbol::ETextOrientation::UNKNOWN;
      };

      inline std::ostream& operator<<(std::ostream& s, const SUpdateSymbolTextMessage& rhs)
      {
        s << "SymbolID: " << rhs.SymbolID << std::endl;
        s << "FontID: " << rhs.FontID << std::endl;
        s << "FontSize: " << std::to_string(rhs.FontSize) << std::endl;
        s << "Alignment: \n" << (int)rhs.Alignment << std::endl;
        s << "Orientation: \n" << (int)rhs.Orientation << std::endl;
        return s;
      }

      struct SSetSymbolColorMessage
      {
        sbio::symbol::SymbolID SymbolID = sbio::symbol::UnknownSymbolID;
        sbio::SColor4f Color;
      };

      inline std::ostream& operator<<(std::ostream& s, const SSetSymbolColorMessage& rhs)
      {
        s << "SymbolID: " << rhs.SymbolID << std::endl;
        s << "Color: \n" << rhs.Color.r << ", " << rhs.Color.g << ", " << rhs.Color.b << ", " << rhs.Color.a << std::endl;
        return s;
      }

      struct SDestroySymbolMessage
      {
        sbio::symbol::SymbolID SymbolID = sbio::symbol::UnknownSymbolID;
      };

      inline std::ostream& operator<<(std::ostream& s, const SDestroySymbolMessage& rhs)
      {
        s << "SymbolID: " << rhs.SymbolID << std::endl;
        return s;
      }

      struct SCreateSymbolCircleMessage
      {
        sbio::symbol::SymbolID SymbolID = sbio::symbol::UnknownSymbolID;
      };

      inline std::ostream& operator<<(std::ostream& s, const SCreateSymbolCircleMessage& rhs)
      {
        s << "SymbolID: " << rhs.SymbolID << std::endl;
        return s;
      }

      struct SUpdateSymbolCircleMessage
      {
        sbio::symbol::SymbolID SymbolID = sbio::symbol::UnknownSymbolID;
        uint32_t NumElements = {0};
        float LineWidth = {0};
        uint16_t StipplePattern = {0};
        float StipplePatternLength = {0};
      };

      inline std::ostream& operator<<(std::ostream& s, const SUpdateSymbolCircleMessage& rhs)
      {
        s << "SymbolID: " << rhs.SymbolID << std::endl;
        s << "NumElements: " << std::to_string(rhs.NumElements) << std::endl;
        s << "LineWidth: " << std::to_string(rhs.LineWidth) << std::endl;
        s << "StipplePattern: " << std::to_string(rhs.StipplePattern) << std::endl;
        s << "StipplePatternLength: " << std::to_string(rhs.StipplePatternLength) << std::endl;
        return s;
      }

      struct SUpdateSymbolCircleElementMessage
      {
        sbio::symbol::SymbolID SymbolID = sbio::symbol::UnknownSymbolID;
        uint32_t ElementIndex = {0};
        sbio::STextureCoordinateUV CenterUV;
        float Radius = {0};
        float StartAngle = {0};
        float EndAngle = {0};
      };

      inline std::ostream& operator<<(std::ostream& s, const SUpdateSymbolCircleElementMessage& rhs)
      {
        s << "SymbolID: " << rhs.SymbolID << std::endl;
        s << "ElementIndex: " << std::to_string(rhs.ElementIndex) << std::endl;
        s << "CenterUV: \n" << rhs.CenterUV.U << ", " << rhs.CenterUV.V << std::endl;
        s << "Radius: " << std::to_string(rhs.Radius) << std::endl;
        s << "StartAngle: " << std::to_string(rhs.StartAngle) << std::endl;
        s << "EndAngle: " << std::to_string(rhs.EndAngle) << std::endl;
        return s;
      }

      struct SUpdateSymbolCircleFilledMessage
      {
        sbio::symbol::SymbolID SymbolID = sbio::symbol::UnknownSymbolID;
        uint32_t NumElements = {0};
      };

      inline std::ostream& operator<<(std::ostream& s, const SUpdateSymbolCircleFilledMessage& rhs)
      {
        s << "SymbolID: " << rhs.SymbolID << std::endl;
        s << "NumElements: " << std::to_string(rhs.NumElements) << std::endl;
        return s;
      }

      struct SUpdateSymbolCircleFilledElementMessage
      {
        sbio::symbol::SymbolID SymbolID = sbio::symbol::UnknownSymbolID;
        uint32_t ElementIndex = {0};
        sbio::STextureCoordinateUV CenterUV;
        float Radius = {0};
        float InnerRadius = {0};
        float StartAngle = {0};
        float EndAngle = {0};
      };

      inline std::ostream& operator<<(std::ostream& s, const SUpdateSymbolCircleFilledElementMessage& rhs)
      {
        s << "SymbolID: " << rhs.SymbolID << std::endl;
        s << "ElementIndex: " << std::to_string(rhs.ElementIndex) << std::endl;
        s << "CenterUV: \n" << rhs.CenterUV.U << ", " << rhs.CenterUV.V << std::endl;
        s << "Radius: " << std::to_string(rhs.Radius) << std::endl;
        s << "InnerRadius: " << std::to_string(rhs.InnerRadius) << std::endl;
        s << "StartAngle: " << std::to_string(rhs.StartAngle) << std::endl;
        s << "EndAngle: " << std::to_string(rhs.EndAngle) << std::endl;
        return s;
      }

      struct SCreateSymbolTexturedCircleMessage
      {
        sbio::symbol::SymbolID SymbolID = sbio::symbol::UnknownSymbolID;
      };

      inline std::ostream& operator<<(std::ostream& s, const SCreateSymbolTexturedCircleMessage& rhs)
      {
        s << "SymbolID: " << rhs.SymbolID << std::endl;
        return s;
      }

      struct SUpdateSymbolTexturedCircleMessage
      {
        sbio::symbol::SymbolID SymbolID = sbio::symbol::UnknownSymbolID;
        sbio::TextureID TextureID = sbio::UnknownTextureID;
        sbio::symbol::ETextureFilterMode TextureFilterMode = sbio::symbol::ETextureFilterMode::UNKNOWN;
        sbio::symbol::ETextureWrapMode TextureWrapMode = sbio::symbol::ETextureWrapMode::UNKNOWN;
        uint32_t NumCircles = {0};
      };

      inline std::ostream& operator<<(std::ostream& s, const SUpdateSymbolTexturedCircleMessage& rhs)
      {
        s << "SymbolID: " << rhs.SymbolID << std::endl;
        s << "TextureID: " << rhs.TextureID << std::endl;
        s << "TextureFilterMode: \n" << (int)rhs.TextureFilterMode << std::endl;
        s << "TextureWrapMode: \n" << (int)rhs.TextureWrapMode << std::endl;
        s << "NumCircles: " << std::to_string(rhs.NumCircles) << std::endl;
        return s;
      }

      struct SUpdateTexturedCircleMessage
      {
        sbio::symbol::SymbolID SymbolID = sbio::symbol::UnknownSymbolID;
        uint32_t CircleIndex = {0};
        sbio::STextureCoordinateUV CenterUV;
        float Radius = {0};
        float StartAngle = {0};
        float EndAngle = {0};
        sbio::STextureCoordinateUV CenterTextureUV;
        float TextureMapRadius = {0};
        float TextureMapRotation = {0};
      };

      inline std::ostream& operator<<(std::ostream& s, const SUpdateTexturedCircleMessage& rhs)
      {
        s << "SymbolID: " << rhs.SymbolID << std::endl;
        s << "CircleIndex: " << std::to_string(rhs.CircleIndex) << std::endl;
        s << "CenterUV: \n" << rhs.CenterUV.U << ", " << rhs.CenterUV.V << std::endl;
        s << "Radius: " << std::to_string(rhs.Radius) << std::endl;
        s << "StartAngle: " << std::to_string(rhs.StartAngle) << std::endl;
        s << "EndAngle: " << std::to_string(rhs.EndAngle) << std::endl;
        s << "CenterTextureUV: \n" << rhs.CenterTextureUV.U << ", " << rhs.CenterTextureUV.V << std::endl;
        s << "TextureMapRadius: " << std::to_string(rhs.TextureMapRadius) << std::endl;
        s << "TextureMapRotation: " << std::to_string(rhs.TextureMapRotation) << std::endl;
        return s;
      }

      struct SCreateSymbolPolygonMessage
      {
        sbio::symbol::SymbolID SymbolID = sbio::symbol::UnknownSymbolID;
      };

      inline std::ostream& operator<<(std::ostream& s, const SCreateSymbolPolygonMessage& rhs)
      {
        s << "SymbolID: " << rhs.SymbolID << std::endl;
        return s;
      }

      struct SUpdateSymbolPolygonMessage
      {
        sbio::symbol::SymbolID SymbolID = sbio::symbol::UnknownSymbolID;
        uint16_t StipplePattern = {0};
        sbio::symbol::EPrimitiveType Primitive = sbio::symbol::EPrimitiveType::UNKNOWN;
        float LineWidth = {0};
        float StipplePatternLength = {0};
        uint32_t NumVertices = {0};
      };

      inline std::ostream& operator<<(std::ostream& s, const SUpdateSymbolPolygonMessage& rhs)
      {
        s << "SymbolID: " << rhs.SymbolID << std::endl;
        s << "StipplePattern: " << std::to_string(rhs.StipplePattern) << std::endl;
        s << "Primitive: \n" << (int)rhs.Primitive << std::endl;
        s << "LineWidth: " << std::to_string(rhs.LineWidth) << std::endl;
        s << "StipplePatternLength: " << std::to_string(rhs.StipplePatternLength) << std::endl;
        s << "NumVertices: " << std::to_string(rhs.NumVertices) << std::endl;
        return s;
      }

      struct SSetSymbolPolygonVertexMessage
      {
        sbio::symbol::SymbolID SymbolID = sbio::symbol::UnknownSymbolID;
        uint32_t VertexIndex = {0};
        float X = {0};
        float Y = {0};
      };

      inline std::ostream& operator<<(std::ostream& s, const SSetSymbolPolygonVertexMessage& rhs)
      {
        s << "SymbolID: " << rhs.SymbolID << std::endl;
        s << "VertexIndex: " << std::to_string(rhs.VertexIndex) << std::endl;
        s << "X: " << std::to_string(rhs.X) << std::endl;
        s << "Y: " << std::to_string(rhs.Y) << std::endl;
        return s;
      }

      struct SCreateSymbolTexturedPolygonMessage
      {
        sbio::symbol::SymbolID SymbolID = sbio::symbol::UnknownSymbolID;
      };

      inline std::ostream& operator<<(std::ostream& s, const SCreateSymbolTexturedPolygonMessage& rhs)
      {
        s << "SymbolID: " << rhs.SymbolID << std::endl;
        return s;
      }

      struct SUpdateSymbolTexturedPolygonMessage
      {
        sbio::symbol::SymbolID SymbolID = sbio::symbol::UnknownSymbolID;
        sbio::symbol::EPrimitiveType Primitive = sbio::symbol::EPrimitiveType::UNKNOWN;
        sbio::TextureID TextureID = sbio::UnknownTextureID;
        sbio::symbol::ETextureFilterMode TextureFilterMode = sbio::symbol::ETextureFilterMode::UNKNOWN;
        sbio::symbol::ETextureWrapMode TextureWrapMode = sbio::symbol::ETextureWrapMode::UNKNOWN;
        uint32_t NumVertices = {0};
      };

      inline std::ostream& operator<<(std::ostream& s, const SUpdateSymbolTexturedPolygonMessage& rhs)
      {
        s << "SymbolID: " << rhs.SymbolID << std::endl;
        s << "Primitive: \n" << (int)rhs.Primitive << std::endl;
        s << "TextureID: " << rhs.TextureID << std::endl;
        s << "TextureFilterMode: \n" << (int)rhs.TextureFilterMode << std::endl;
        s << "TextureWrapMode: \n" << (int)rhs.TextureWrapMode << std::endl;
        s << "NumVertices: " << std::to_string(rhs.NumVertices) << std::endl;
        return s;
      }

      struct SSetSymbolTexturedPolygonVertexMessage
      {
        sbio::symbol::SymbolID SymbolID = sbio::symbol::UnknownSymbolID;
        uint32_t VertexIndex = {0};
        sbio::STextureCoordinateUV VertexUV;
        sbio::STextureCoordinateST TextureCoordinateST;
      };

      inline std::ostream& operator<<(std::ostream& s, const SSetSymbolTexturedPolygonVertexMessage& rhs)
      {
        s << "SymbolID: " << rhs.SymbolID << std::endl;
        s << "VertexIndex: " << std::to_string(rhs.VertexIndex) << std::endl;
        s << "VertexUV: \n" << rhs.VertexUV.U << ", " << rhs.VertexUV.V << std::endl;
        s << "TextureCoordinateST: \n" << rhs.TextureCoordinateST.S << ", " << rhs.TextureCoordinateST.T << std::endl;
        return s;
      }

      struct SUpdateEntityBillboardSymbolSurfaceMessage
      {
        sbio::symbol::SymbolSurfaceID SurfaceID = sbio::symbol::UnknownSymbolSurfaceID;
        sbio::EntityID EntityID = sbio::UnknownEntityID;
        sbio::STextureCoordinateUV uvMin;
        sbio::STextureCoordinateUV uvMax;
        sbio::math::BodyCoordinates Offset;
        float Width = {0};
        float Height = {0};
      };

      inline std::ostream& operator<<(std::ostream& s, const SUpdateEntityBillboardSymbolSurfaceMessage& rhs)
      {
        s << "SurfaceID: " << rhs.SurfaceID << std::endl;
        s << "EntityID: " << rhs.EntityID << std::endl;
        s << "uvMin: \n" << rhs.uvMin.U << ", " << rhs.uvMin.V << std::endl;
        s << "uvMax: \n" << rhs.uvMax.U << ", " << rhs.uvMax.V << std::endl;
        s << "Offset: \n" << rhs.Offset[0] << ", " << rhs.Offset[1] << ", " << rhs.Offset[2] << std::endl;
        s << "Width: " << std::to_string(rhs.Width) << std::endl;
        s << "Height: " << std::to_string(rhs.Height) << std::endl;
        return s;
      }

      struct SCreateSymbolSurfaceMessage
      {
        sbio::symbol::SymbolSurfaceID SurfaceID = sbio::symbol::UnknownSymbolSurfaceID;
      };

      inline std::ostream& operator<<(std::ostream& s, const SCreateSymbolSurfaceMessage& rhs)
      {
        s << "SurfaceID: " << rhs.SurfaceID << std::endl;
        return s;
      }

      struct SDestroySymbolSurfaceMessage
      {
        sbio::symbol::SymbolSurfaceID SurfaceID = sbio::symbol::UnknownSymbolSurfaceID;
      };

      inline std::ostream& operator<<(std::ostream& s, const SDestroySymbolSurfaceMessage& rhs)
      {
        s << "SurfaceID: " << rhs.SurfaceID << std::endl;
        return s;
      }

      struct SUpdateSymbolSurfaceMessage
      {
        sbio::symbol::SymbolSurfaceID SurfaceID = sbio::symbol::UnknownSymbolSurfaceID;
        sbio::EntityID EntityID = sbio::UnknownEntityID;
        sbio::STextureCoordinateUV uvMin;
        sbio::STextureCoordinateUV uvMax;
        sbio::math::BodyCoordinates Offset;
        float Roll = {0};
        float Pitch = {0};
        float Yaw = {0};
        float Width = {0};
        float Height = {0};
      };

      inline std::ostream& operator<<(std::ostream& s, const SUpdateSymbolSurfaceMessage& rhs)
      {
        s << "SurfaceID: " << rhs.SurfaceID << std::endl;
        s << "EntityID: " << rhs.EntityID << std::endl;
        s << "uvMin: \n" << rhs.uvMin.U << ", " << rhs.uvMin.V << std::endl;
        s << "uvMax: \n" << rhs.uvMax.U << ", " << rhs.uvMax.V << std::endl;
        s << "Offset: \n" << rhs.Offset[0] << ", " << rhs.Offset[1] << ", " << rhs.Offset[2] << std::endl;
        s << "Roll: " << std::to_string(rhs.Roll) << std::endl;
        s << "Pitch: " << std::to_string(rhs.Pitch) << std::endl;
        s << "Yaw: " << std::to_string(rhs.Yaw) << std::endl;
        s << "Width: " << std::to_string(rhs.Width) << std::endl;
        s << "Height: " << std::to_string(rhs.Height) << std::endl;
        return s;
      }

      struct SUpdateViewSymbolSurfaceMessage
      {
        sbio::symbol::SymbolSurfaceID SurfaceID = sbio::symbol::UnknownSymbolSurfaceID;
        sbio::ViewID ViewID = sbio::UnknownViewID;
        sbio::STextureCoordinateUV uvMin;
        sbio::STextureCoordinateUV uvMax;
        float Left = {0};
        float Right = {0};
        float Top = {0};
        float Bottom = {0};
      };

      inline std::ostream& operator<<(std::ostream& s, const SUpdateViewSymbolSurfaceMessage& rhs)
      {
        s << "SurfaceID: " << rhs.SurfaceID << std::endl;
        s << "ViewID: " << rhs.ViewID << std::endl;
        s << "uvMin: \n" << rhs.uvMin.U << ", " << rhs.uvMin.V << std::endl;
        s << "uvMax: \n" << rhs.uvMax.U << ", " << rhs.uvMax.V << std::endl;
        s << "Left: " << std::to_string(rhs.Left) << std::endl;
        s << "Right: " << std::to_string(rhs.Right) << std::endl;
        s << "Top: " << std::to_string(rhs.Top) << std::endl;
        s << "Bottom: " << std::to_string(rhs.Bottom) << std::endl;
        return s;
      }

      struct SSetSymbolVisibleMessage
      {
        sbio::symbol::SymbolID SymbolID = sbio::symbol::UnknownSymbolID;
        bool Visible = false;
      };

      inline std::ostream& operator<<(std::ostream& s, const SSetSymbolVisibleMessage& rhs)
      {
        s << "SymbolID: " << rhs.SymbolID << std::endl;
        s << "Visible: " << std::to_string(rhs.Visible) << std::endl;
        return s;
      }

      struct SSetSymbolAttachedMessage
      {
        sbio::symbol::SymbolID SymbolID = sbio::symbol::UnknownSymbolID;
        sbio::symbol::SymbolID ParentSymbolID = sbio::symbol::UnknownSymbolID;
      };

      inline std::ostream& operator<<(std::ostream& s, const SSetSymbolAttachedMessage& rhs)
      {
        s << "SymbolID: " << rhs.SymbolID << std::endl;
        s << "ParentSymbolID: " << rhs.ParentSymbolID << std::endl;
        return s;
      }

      struct SSetSymbolUnattachedMessage
      {
        sbio::symbol::SymbolID SymbolID = sbio::symbol::UnknownSymbolID;
      };

      inline std::ostream& operator<<(std::ostream& s, const SSetSymbolUnattachedMessage& rhs)
      {
        s << "SymbolID: " << rhs.SymbolID << std::endl;
        return s;
      }

      struct SSetSymbolSurfaceMessage
      {
        sbio::symbol::SymbolID SymbolID = sbio::symbol::UnknownSymbolID;
        sbio::symbol::SymbolSurfaceID SurfaceID = sbio::symbol::UnknownSymbolSurfaceID;
      };

      inline std::ostream& operator<<(std::ostream& s, const SSetSymbolSurfaceMessage& rhs)
      {
        s << "SymbolID: " << rhs.SymbolID << std::endl;
        s << "SurfaceID: " << rhs.SurfaceID << std::endl;
        return s;
      }

      struct SSetTopLevelSymbolTransformMessage
      {
        sbio::symbol::SymbolID SymbolID = sbio::symbol::UnknownSymbolID;
        sbio::math::Degrees Rotation = sbio::math::UnknownDegrees;//the IG shall orient the symbol with respect to the symbol surface’s local 2D coordinate system
      };

      inline std::ostream& operator<<(std::ostream& s, const SSetTopLevelSymbolTransformMessage& rhs)
      {
        s << "SymbolID: " << rhs.SymbolID << std::endl;
        s << "Rotation: " << rhs.Rotation.Value() << std::endl;
        return s;
      }

      struct SSetChildSymbolTransformMessage
      {
        sbio::symbol::SymbolID SymbolID = sbio::symbol::UnknownSymbolID;
        sbio::math::Degrees Rotation = sbio::math::UnknownDegrees;//the IG shall orient the symbol with respect to the parent symbol’s local coordinate system
      };

      inline std::ostream& operator<<(std::ostream& s, const SSetChildSymbolTransformMessage& rhs)
      {
        s << "SymbolID: " << rhs.SymbolID << std::endl;
        s << "Rotation: " << rhs.Rotation.Value() << std::endl;
        return s;
      }

      struct SUpdateSymbolMessage
      {
        sbio::symbol::SymbolID SymbolID = sbio::symbol::UnknownSymbolID;
        uint16_t Layer = {0};
        sbio::STextureCoordinateUV PositionUV;
        float ScaleU = {0};
        float ScaleV = {0};
      };

      inline std::ostream& operator<<(std::ostream& s, const SUpdateSymbolMessage& rhs)
      {
        s << "SymbolID: " << rhs.SymbolID << std::endl;
        s << "Layer: " << std::to_string(rhs.Layer) << std::endl;
        s << "PositionUV: \n" << rhs.PositionUV.U << ", " << rhs.PositionUV.V << std::endl;
        s << "ScaleU: " << std::to_string(rhs.ScaleU) << std::endl;
        s << "ScaleV: " << std::to_string(rhs.ScaleV) << std::endl;
        return s;
      }

      struct SSetSymbolComponentStateMessage
      {
        sbio::symbol::SymbolID SymbolID = sbio::symbol::UnknownSymbolID;
        sbio::cigi::CigiComponentID ComponentID = sbio::cigi::UnknownCigiComponentID;
        int32_t ComponentState = {0};
        SComponentData ComponentData;
      };

      inline std::ostream& operator<<(std::ostream& s, const SSetSymbolComponentStateMessage& rhs)
      {
        s << "SymbolID: " << rhs.SymbolID << std::endl;
        s << "ComponentID: " << rhs.ComponentID << std::endl;
        s << "ComponentState: " << std::to_string(rhs.ComponentState) << std::endl;
        s << "ComponentData: \n" << rhs.ComponentData << std::endl;
        return s;
      }

      struct SSetSymbolSurfaceComponentStateMessage
      {
        sbio::symbol::SymbolSurfaceID SymbolSurfaceID = sbio::symbol::UnknownSymbolSurfaceID;
        sbio::cigi::CigiComponentID ComponentID = sbio::cigi::UnknownCigiComponentID;
        int32_t ComponentState = {0};
        SComponentData ComponentData;
      };

      inline std::ostream& operator<<(std::ostream& s, const SSetSymbolSurfaceComponentStateMessage& rhs)
      {
        s << "SymbolSurfaceID: " << rhs.SymbolSurfaceID << std::endl;
        s << "ComponentID: " << rhs.ComponentID << std::endl;
        s << "ComponentState: " << std::to_string(rhs.ComponentState) << std::endl;
        s << "ComponentData: \n" << rhs.ComponentData << std::endl;
        return s;
      }

      struct SCreateSymbolFromTemplateMessage
      {
        sbio::symbol::SymbolID SymbolID = sbio::symbol::UnknownSymbolID;
        uint32_t TemplateID = {0};
      };

      inline std::ostream& operator<<(std::ostream& s, const SCreateSymbolFromTemplateMessage& rhs)
      {
        s << "SymbolID: " << rhs.SymbolID << std::endl;
        s << "TemplateID: " << std::to_string(rhs.TemplateID) << std::endl;
        return s;
      }
    }

    namespace celestial
    {
      /**
       * @brief Celestial sphere, ephemeris, and date/time update messages.
       */

      struct SUpdateCelestialSphereMessage
      {
        bool MoonEnabled = false;
        bool StarFieldEnabled = false;
        float StarfieldIntensity = {0};
        bool SunEnabled = false;
        bool EphemerisEnabled = false;
      };

      inline std::ostream& operator<<(std::ostream& s, const SUpdateCelestialSphereMessage& rhs)
      {
        s << "MoonEnabled: " << std::to_string(rhs.MoonEnabled) << std::endl;
        s << "StarFieldEnabled: " << std::to_string(rhs.StarFieldEnabled) << std::endl;
        s << "StarfieldIntensity: " << std::to_string(rhs.StarfieldIntensity) << std::endl;
        s << "SunEnabled: " << std::to_string(rhs.SunEnabled) << std::endl;
        s << "EphemerisEnabled: " << std::to_string(rhs.EphemerisEnabled) << std::endl;
        return s;
      }

      struct SUpdateDateTimeMessage
      {
        sbio::SDate Date;
        sbio::STime Time;
      };

      inline std::ostream& operator<<(std::ostream& s, const SUpdateDateTimeMessage& rhs)
      {
        s << "Year: " << rhs.Date.year << std::endl;
        s << "Month: " << rhs.Date.month << std::endl;
        s << "Day: " << rhs.Date.day << std::endl;
        s << "Hour: " << rhs.Time.hour << std::endl;
        s << "Minute: " << rhs.Time.minute << std::endl;
        s << "Minute: " << rhs.Time.seconds << std::endl;
        return s;
      }

      struct SSetCelestialSphereComponentStateMessage
      {
        sbio::CelestialSphereID CelestialSphereID = sbio::UnknownCelestialSphereID;
        sbio::cigi::CigiComponentID ComponentID = sbio::cigi::UnknownCigiComponentID;
        int32_t ComponentState = {0};
        SComponentData ComponentData;
      };

      inline std::ostream& operator<<(std::ostream& s, const SSetCelestialSphereComponentStateMessage& rhs)
      {
        s << "CelestialSphereID: " << rhs.CelestialSphereID << std::endl;
        s << "ComponentID: " << rhs.ComponentID << std::endl;
        s << "ComponentState: " << std::to_string(rhs.ComponentState) << std::endl;
        s << "ComponentData: \n" << rhs.ComponentData << std::endl;
        return s;
      }
    }

    namespace sensor
    {
      /**
       * @brief Sensor, motion tracker, and sensor response messages.
       */

      struct SUpdateSensorMessage
      {
        sbio::cigi::SensorID SensorID = sbio::cigi::UnknownSensorID;
        sbio::cigi::ETrackMode eTrackMode = sbio::cigi::ETrackMode::UNKNOWN;
        sbio::cigi::EPolarity ePolarity = sbio::cigi::EPolarity::UNKNOWN;
        bool bSensorOn = false;
        bool bLineByLineDropoutEnabled = false;
        bool bAutomaticGain = false;
        sbio::cigi::ESensorTrack eSensorTrack = sbio::cigi::ESensorTrack::UNKNOWN;
        bool bExtendedResponse = false;
        sbio::ViewID ViewID = sbio::UnknownViewID;
        sbio::cigi::SensorGain Gain = sbio::cigi::UnknownSensorGain;
        sbio::cigi::SensorLevel Level = sbio::cigi::UnknownSensorLevel;
        float ACCoupling = {0};
        sbio::cigi::SensorNoise Noise = sbio::cigi::UnknownSensorNoise;
      };

      inline std::ostream& operator<<(std::ostream& s, const SUpdateSensorMessage& rhs)
      {
        s << "SensorID: " << rhs.SensorID << std::endl;
        s << "eTrackMode: \n" << (int)rhs.eTrackMode << std::endl;
        s << "ePolarity: \n" << (int)rhs.ePolarity << std::endl;
        s << "bSensorOn: " << std::to_string(rhs.bSensorOn) << std::endl;
        s << "bLineByLineDropoutEnabled: " << std::to_string(rhs.bLineByLineDropoutEnabled) << std::endl;
        s << "bAutomaticGain: " << std::to_string(rhs.bAutomaticGain) << std::endl;
        s << "eSensorTrack: \n" << (int)rhs.eSensorTrack << std::endl;
        s << "bExtendedResponse: " << std::to_string(rhs.bExtendedResponse) << std::endl;
        s << "ViewID: " << rhs.ViewID << std::endl;
        s << "Gain: " << rhs.Gain << std::endl;
        s << "Level: " << rhs.Level << std::endl;
        s << "ACCoupling: " << std::to_string(rhs.ACCoupling) << std::endl;
        s << "Noise: " << rhs.Noise << std::endl;
        return s;
      }

      struct SUpdateSensorComponentMessage
      {
        sbio::cigi::SensorID SensorID = sbio::cigi::UnknownSensorID;
        sbio::cigi::CigiComponentID ComponentID = sbio::cigi::UnknownCigiComponentID;
        uint32_t ComponentState = {0};
        SComponentData ComponentData;
      };

      inline std::ostream& operator<<(std::ostream& s, const SUpdateSensorComponentMessage& rhs)
      {
        s << "SensorID: " << rhs.SensorID << std::endl;
        s << "ComponentID: " << rhs.ComponentID << std::endl;
        s << "ComponentState: " << std::to_string(rhs.ComponentState) << std::endl;
        s << "ComponentData: \n" << rhs.ComponentData << std::endl;
        return s;
      }

      struct SCreateMotionTrackerViewMessage
      {
        sbio::MotionTrackerID TrackerID = sbio::UnknownMotionTrackerID;
        sbio::ViewID ViewID = sbio::UnknownViewID;
      };

      inline std::ostream& operator<<(std::ostream& s, const SCreateMotionTrackerViewMessage& rhs)
      {
        s << "TrackerID: " << rhs.TrackerID << std::endl;
        s << "ViewID: " << rhs.ViewID << std::endl;
        return s;
      }

      struct SCreateMotionTrackerViewGroupMessage
      {
        sbio::MotionTrackerID TrackerID = sbio::UnknownMotionTrackerID;
        sbio::ViewGroupID ViewGroupID = UnknownViewGroupID;
      };

      inline std::ostream& operator<<(std::ostream& s, const SCreateMotionTrackerViewGroupMessage& rhs)
      {
        s << "TrackerID: " << rhs.TrackerID << std::endl;
        s << "ViewGroupID: " << rhs.ViewGroupID << std::endl;
        return s;
      }

      struct SSetMotionTrackerMessage
      {
        sbio::MotionTrackerID TrackerID = sbio::UnknownMotionTrackerID;
        bool TrackerEnabled = false;
        bool BoresightEnabled = false;
        bool XEnabled = false;
        bool YEnabled = false;
        bool ZEnabled = false;
        bool RollEnabled = false;
      };

      inline std::ostream& operator<<(std::ostream& s, const SSetMotionTrackerMessage& rhs)
      {
        s << "TrackerID: " << rhs.TrackerID << std::endl;
        s << "TrackerEnabled: " << std::to_string(rhs.TrackerEnabled) << std::endl;
        s << "BoresightEnabled: " << std::to_string(rhs.BoresightEnabled) << std::endl;
        s << "XEnabled: " << std::to_string(rhs.XEnabled) << std::endl;
        s << "YEnabled: " << std::to_string(rhs.YEnabled) << std::endl;
        s << "ZEnabled: " << std::to_string(rhs.ZEnabled) << std::endl;
        s << "RollEnabled: " << std::to_string(rhs.RollEnabled) << std::endl;
        return s;
      }

      /**
       * @brief Basic sensor response containing gate geometry and status.
       */
      struct SSensorResponseMessage
      {
        sbio::cigi::SensorID SensorID = sbio::cigi::UnknownSensorID;
        sbio::ViewID ViewID = sbio::UnknownViewID;
        sbio::cigi::ESensorStatus SensorStatus = sbio::cigi::ESensorStatus::UKNOWN;
        sbio::STextureCoordinateUV GateSize;
        sbio::STextureCoordinateUV GatePosition;
      };

      inline std::ostream& operator<<(std::ostream& s, const SSensorResponseMessage& rhs)
      {
        s << "SensorID: " << rhs.SensorID << std::endl;
        s << "ViewID: " << rhs.ViewID << std::endl;
        s << "SensorStatus: \n" << (int)rhs.SensorStatus << std::endl;
        s << "GateSize: \n" << rhs.GateSize.U << ", " << rhs.GateSize.V << std::endl;
        s << "GatePosition: \n" << rhs.GatePosition.U << ", " << rhs.GatePosition.V << std::endl;
        return s;
      }

      /**
       * @brief Extended sensor response including the tracked point in geodetic coordinates.
       */
      struct SSensorExtendedResponseMessage
      {
        sbio::cigi::SensorID SensorID = sbio::cigi::UnknownSensorID;
        sbio::ViewID ViewID = sbio::UnknownViewID;
        sbio::cigi::ESensorStatus SensorStatus = sbio::cigi::ESensorStatus::UKNOWN;
        sbio::STextureCoordinateUV GateSize;
        sbio::STextureCoordinateUV GatePosition;
        sbio::math::SGeodeticCoordinates TrackPointCoordinate;
      };

      inline std::ostream& operator<<(std::ostream& s, const SSensorExtendedResponseMessage& rhs)
      {
        s << "SensorID: " << rhs.SensorID << std::endl;
        s << "ViewID: " << rhs.ViewID << std::endl;
        s << "SensorStatus: \n" << (int)rhs.SensorStatus << std::endl;
        s << "GateSize: \n" << rhs.GateSize.U << ", " << rhs.GateSize.V << std::endl;
        s << "GatePosition: \n" << rhs.GatePosition.U << ", " << rhs.GatePosition.V << std::endl;
        s << "TrackPointCoordinate: \n" << rhs.TrackPointCoordinate.latitude << ", " << rhs.TrackPointCoordinate.longitude << ", " << rhs.TrackPointCoordinate.altitude << std::endl;
        return s;
      }

      /**
       * @brief Extended sensor response that also identifies the tracked entity.
       */
      struct SSensorExtendedEntityResponseMessage
      {
        sbio::cigi::SensorID SensorID = sbio::cigi::UnknownSensorID;
        sbio::ViewID ViewID = sbio::UnknownViewID;
        sbio::EntityID EntityID = sbio::UnknownEntityID;
        sbio::cigi::ESensorStatus SensorStatus = sbio::cigi::ESensorStatus::UKNOWN;
        sbio::STextureCoordinateUV GateSize;
        sbio::STextureCoordinateUV GatePosition;
        sbio::math::SGeodeticCoordinates TrackPointCoordinate;
      };

      inline std::ostream& operator<<(std::ostream& s, const SSensorExtendedEntityResponseMessage& rhs)
      {
        s << "SensorID: " << rhs.SensorID << std::endl;
        s << "ViewID: " << rhs.ViewID << std::endl;
        s << "EntityID: " << rhs.EntityID << std::endl;
        s << "SensorStatus: \n" << (int)rhs.SensorStatus << std::endl;
        s << "GateSize: \n" << rhs.GateSize.U << ", " << rhs.GateSize.V << std::endl;
        s << "GatePosition: \n" << rhs.GatePosition.U << ", " << rhs.GatePosition.V << std::endl;
        s << "TrackPointCoordinate: \n" << rhs.TrackPointCoordinate.latitude << ", " << rhs.TrackPointCoordinate.longitude << ", " << rhs.TrackPointCoordinate.altitude << std::endl;
        return s;
      }
    }

    namespace atmosphere
    {
      /**
       * @brief Atmosphere and layered weather control messages.
       */

      struct SSetAtmosphereEnabledMessage
      {
        bool Enabled = false;
      };

      inline std::ostream& operator<<(std::ostream& s, const SSetAtmosphereEnabledMessage& rhs)
      {
        s << "Enabled: " << std::to_string(rhs.Enabled) << std::endl;
        return s;
      }

      struct SSetAtmosphereMessage
      {
        float Humidity = {0};
        float AirTemperature = {0};
        float VisibilityRange = {0};
        float HorizontalWindSpeed = {0};
        float VerticalWindSpeed = {0};
        float WindDirection = {0};
        float BarometricPressure = {0};
      };

      inline std::ostream& operator<<(std::ostream& s, const SSetAtmosphereMessage& rhs)
      {
        s << "Humidity: " << std::to_string(rhs.Humidity) << std::endl;
        s << "AirTemperature: " << std::to_string(rhs.AirTemperature) << std::endl;
        s << "VisibilityRange: " << std::to_string(rhs.VisibilityRange) << std::endl;
        s << "HorizontalWindSpeed: " << std::to_string(rhs.HorizontalWindSpeed) << std::endl;
        s << "VerticalWindSpeed: " << std::to_string(rhs.VerticalWindSpeed) << std::endl;
        s << "WindDirection: " << std::to_string(rhs.WindDirection) << std::endl;
        s << "BarometricPressure: " << std::to_string(rhs.BarometricPressure) << std::endl;
        return s;
      }

      struct SSetWeatherMessage
      {
        bool WeatherEnabled = false;
        uint16_t LayerID = {0};
        float Humidity = {0};
        sbio::TemperatureCelsius AirTemperature = sbio::UnknownTemperatureCelsius;
        float VisibilityRange = {0};
        float HorizontalWindSpeed = {0};
        float VerticalWindSpeed = {0};
        float WindDirection = {0};
        float BarometricPressure = {0};
        float AerosolConcentration = {0};
        bool BottomScudEnabled = false;
        bool TopScudEnabled = false;
        float TopScudFrequency = {0};
        float BottomScudFrequency = {0};
        bool RandomWindsEnabled = false;
        bool RandomLightningEnabled = false;
        uint16_t CloudType = {0};
        sbio::WeatherSeverity Severity = sbio::UnknownWeatherSeverity;
        float Coverage = {0};
        float BaseElevation = {0};
        float VerticalThickness = {0};
        float TopTransitionBandThickness = {0};
        float BottomTransitionBandThickness = {0};
      };

      inline std::ostream& operator<<(std::ostream& s, const SSetWeatherMessage& rhs)
      {
        s << "WeatherEnabled: " << std::to_string(rhs.WeatherEnabled) << std::endl;
        s << "LayerID: " << std::to_string(rhs.LayerID) << std::endl;
        s << "Humidity: " << std::to_string(rhs.Humidity) << std::endl;
        s << "AirTemperature: " << std::to_string(rhs.AirTemperature.Value()) << std::endl;
        s << "VisibilityRange: " << std::to_string(rhs.VisibilityRange) << std::endl;
        s << "HorizontalWindSpeed: " << std::to_string(rhs.HorizontalWindSpeed) << std::endl;
        s << "VerticalWindSpeed: " << std::to_string(rhs.VerticalWindSpeed) << std::endl;
        s << "WindDirection: " << std::to_string(rhs.WindDirection) << std::endl;
        s << "BarometricPressure: " << std::to_string(rhs.BarometricPressure) << std::endl;
        s << "AerosolConcentration: " << std::to_string(rhs.AerosolConcentration) << std::endl;
        s << "BottomScudEnabled: " << std::to_string(rhs.BottomScudEnabled) << std::endl;
        s << "TopScudEnabled: " << std::to_string(rhs.TopScudEnabled) << std::endl;
        s << "TopScudFrequency: " << std::to_string(rhs.TopScudFrequency) << std::endl;
        s << "BottomScudFrequency: " << std::to_string(rhs.BottomScudFrequency) << std::endl;
        s << "RandomWindsEnabled: " << std::to_string(rhs.RandomWindsEnabled) << std::endl;
        s << "RandomLightningEnabled: " << std::to_string(rhs.RandomLightningEnabled) << std::endl;
        s << "CloudType: " << std::to_string(rhs.CloudType) << std::endl;
        s << "Severity: \n" << rhs.Severity << std::endl;
        s << "Coverage: " << std::to_string(rhs.Coverage) << std::endl;
        s << "BaseElevation: " << std::to_string(rhs.BaseElevation) << std::endl;
        s << "VerticalThickness: " << std::to_string(rhs.VerticalThickness) << std::endl;
        s << "TopTransitionBandThickness: " << std::to_string(rhs.TopTransitionBandThickness) << std::endl;
        s << "BottomTransitionBandThickness: " << std::to_string(rhs.BottomTransitionBandThickness) << std::endl;
        return s;
      }

      struct SSetRegionalLayeredWeatherComponentStateMessage
      {
        sbio::RegionalLayeredWeatherID LayeredWeatherID = sbio::UnknownRegionalLayeredWeatherID;
        sbio::cigi::CigiComponentID ComponentID = sbio::cigi::UnknownCigiComponentID;
        int32_t ComponentState = {0};
        SComponentData ComponentData;
      };

      inline std::ostream& operator<<(std::ostream& s, const SSetRegionalLayeredWeatherComponentStateMessage& rhs)
      {
        s << "LayeredWeatherID: " << rhs.LayeredWeatherID << std::endl;
        s << "ComponentID: " << rhs.ComponentID << std::endl;
        s << "ComponentState: " << std::to_string(rhs.ComponentState) << std::endl;
        s << "ComponentData: \n" << rhs.ComponentData << std::endl;
        return s;
      }

      struct SSetGlobalLayeredWeatherComponentStateMessage
      {
        sbio::GlobalLayeredWeatherID LayeredWeatherID = sbio::UnknownGlobalLayeredWeatherID;
        sbio::cigi::CigiComponentID ComponentID = sbio::cigi::UnknownCigiComponentID;
        int32_t ComponentState = {0};
        SComponentData ComponentData;
      };

      inline std::ostream& operator<<(std::ostream& s, const SSetGlobalLayeredWeatherComponentStateMessage& rhs)
      {
        s << "LayeredWeatherID: " << rhs.LayeredWeatherID << std::endl;
        s << "ComponentID: " << rhs.ComponentID << std::endl;
        s << "ComponentState: " << std::to_string(rhs.ComponentState) << std::endl;
        s << "ComponentData: \n" << rhs.ComponentData << std::endl;
        return s;
      }

      struct SSetAtmosphereComponentStateMessage
      {
        sbio::AtmosphereID AtmosphereID = sbio::UnknownAtmosphereID;
        sbio::cigi::CigiComponentID ComponentID = sbio::cigi::UnknownCigiComponentID;
        int32_t ComponentState = {0};
        SComponentData ComponentData;
      };

      inline std::ostream& operator<<(std::ostream& s, const SSetAtmosphereComponentStateMessage& rhs)
      {
        s << "AtmosphereID: " << rhs.AtmosphereID << std::endl;
        s << "ComponentID: " << rhs.ComponentID << std::endl;
        s << "ComponentState: " << std::to_string(rhs.ComponentState) << std::endl;
        s << "ComponentData: \n" << rhs.ComponentData << std::endl;
        return s;
      }
    }

    namespace ocean
    {
      /**
       * @brief Maritime surface condition and maritime component-state messages.
       */

      struct SSetMaritimeSurfaceConditionsMessage
      {
        float SeaSurfaceHeight = {0};
        float SurfaceWaterTemperature = {0};
        float SurfaceClarity = {0};
        bool WhitecapEnabled = false;
      };

      inline std::ostream& operator<<(std::ostream& s, const SSetMaritimeSurfaceConditionsMessage& rhs)
      {
        s << "SeaSurfaceHeight: " << std::to_string(rhs.SeaSurfaceHeight) << std::endl;
        s << "SurfaceWaterTemperature: " << std::to_string(rhs.SurfaceWaterTemperature) << std::endl;
        s << "SurfaceClarity: " << std::to_string(rhs.SurfaceClarity) << std::endl;
        s << "WhitecapEnabled: " << std::to_string(rhs.WhitecapEnabled) << std::endl;
        return s;
      }

      struct SSetRegionMaritimeComponentStateMessage
      {
        sbio::RegionID RegionID = sbio::UnknownRegionID;
        sbio::cigi::CigiComponentID ComponentID = sbio::cigi::UnknownCigiComponentID;
        int32_t ComponentState = {0};
        SComponentData ComponentData;
      };

      inline std::ostream& operator<<(std::ostream& s, const SSetRegionMaritimeComponentStateMessage& rhs)
      {
        s << "RegionID: " << rhs.RegionID << std::endl;
        s << "ComponentID: " << rhs.ComponentID << std::endl;
        s << "ComponentState: " << std::to_string(rhs.ComponentState) << std::endl;
        s << "ComponentData: \n" << rhs.ComponentData << std::endl;
        return s;
      }

      struct SSetGlobalMaritimeComponentStateMessage
      {
        sbio::GlobalSeaSurfaceID MaritimeID = sbio::UnknownGlobalSeaSurfaceID;
        sbio::cigi::CigiComponentID ComponentID = sbio::cigi::UnknownCigiComponentID;
        int32_t ComponentState = {0};
        SComponentData ComponentData;
      };

      inline std::ostream& operator<<(std::ostream& s, const SSetGlobalMaritimeComponentStateMessage& rhs)
      {
        s << "MaritimeID: " << rhs.MaritimeID << std::endl;
        s << "ComponentID: " << rhs.ComponentID << std::endl;
        s << "ComponentState: " << std::to_string(rhs.ComponentState) << std::endl;
        s << "ComponentData: \n" << rhs.ComponentData << std::endl;
        return s;
      }
    }

    namespace earth
    {
      /**
       * @brief Earth reference model update messages.
       */

      struct SSetEarthReferenceModelMessage
      {
        double EquatorialRadius = {0};
        double Flattening = {0};
      };

      inline std::ostream& operator<<(std::ostream& s, const SSetEarthReferenceModelMessage& rhs)
      {
        s << "EquatorialRadius: " << std::to_string(rhs.EquatorialRadius) << std::endl;
        s << "Flattening: " << std::to_string(rhs.Flattening) << std::endl;
        return s;
      }
    }

    namespace system
    {
      /**
       * @brief Event, system, and image-generator notification messages.
       */

      struct SSetEventComponentStateMessage
      {
        sbio::ComponentEventID EventID = sbio::UnknownComponentEventID;
        sbio::cigi::CigiComponentID ComponentID = sbio::cigi::UnknownCigiComponentID;
        int32_t ComponentState = {0};
        SComponentData ComponentData;
      };

      inline std::ostream& operator<<(std::ostream& s, const SSetEventComponentStateMessage& rhs)
      {
        s << "EventID: " << rhs.EventID << std::endl;
        s << "ComponentID: " << rhs.ComponentID << std::endl;
        s << "ComponentState: " << std::to_string(rhs.ComponentState) << std::endl;
        s << "ComponentData: \n" << rhs.ComponentData << std::endl;
        return s;
      }

      struct SEventNotificationMessage
      {
        uint16_t EventID = {0};
        uint32_t EventData1 = {0};
        uint32_t EventData2 = {0};
        uint32_t EventData3 = {0};
      };

      inline std::ostream& operator<<(std::ostream& s, const SEventNotificationMessage& rhs)
      {
        s << "EventID: " << std::to_string(rhs.EventID) << std::endl;
        s << "EventData1: " << std::to_string(rhs.EventData1) << std::endl;
        s << "EventData2: " << std::to_string(rhs.EventData2) << std::endl;
        s << "EventData3: " << std::to_string(rhs.EventData3) << std::endl;
        return s;
      }

      struct SSetSystemComponentStateMessage
      {
        sbio::SystemID SystemID = sbio::UnknownSystemID;
        sbio::cigi::CigiComponentID ComponentID = sbio::cigi::UnknownCigiComponentID;
        int32_t ComponentState = {0};
        SComponentData ComponentData;
      };

      inline std::ostream& operator<<(std::ostream& s, const SSetSystemComponentStateMessage& rhs)
      {
        s << "SystemID: " << rhs.SystemID << std::endl;
        s << "ComponentID: " << rhs.ComponentID << std::endl;
        s << "ComponentState: " << std::to_string(rhs.ComponentState) << std::endl;
        s << "ComponentData: \n" << rhs.ComponentData << std::endl;
        return s;
      }

      /**
       * @brief Carries an image-generator-defined notification message and raw payload words.
       */
      struct SImageGeneratorNotificationMessage
      {
        uint32_t MessageID = {0};
        uint16_t Data[100];
      };

      inline std::ostream& operator<<(std::ostream& s, const SImageGeneratorNotificationMessage& rhs)
      {
        s << "MessageID: " << std::to_string(rhs.MessageID) << std::endl;
        ;
        return s;
      }
    }

    namespace network
    {
      /**
       * @brief Host connectivity status messages exchanged with the image generator layer.
       */
      struct SHostConnectedMessage
      {
        std::string sHostIP;
      };

      struct SHostDisconnectedMessage
      {
        std::string sHostIP;
      };
    }
  }
}

#endif//#ifndef SIMBLOCKS_IMAGE_GENERATOR_MESSAGES_H

//The source code in this file is licensed under the MIT License. See the LICENSE text file for full terms.
//Refer all inquiries to sales@simblocks.io
//Copyright SimBlocks LLC 2016-2026
