//Copyright SimBlocks LLC 2016-2026
// This file has been generated by idlgen.exe. Do not modify this file directly!

#include "EngineLib/ImageGeneratorEventMessenger.h"
#include "EngineLib/ImageGeneratorMessages.h"
#include "GlobalHeaders/CommonTypes.h"
using namespace sbio::ig;

CImageGeneratorEventMessenger::CImageGeneratorEventMessenger(IImageGeneratorEventHandler* pEventHandler) : m_pEventHandler(pEventHandler)
{
}

bool CImageGeneratorEventMessenger::IsPointInEntityVolume(const sbio::math::GeocentricCoordinates& point, sbio::EntityID entityID) const
{
  return m_pEventHandler != nullptr && m_pEventHandler->IsPointInEntityVolume(point, entityID);
}

bool CImageGeneratorEventMessenger::GetMotionTrackerPosition(sbio::MotionTrackerID trackerID, sbio::math::Vec3& offset, sbio::math::TBodyEulerRotation& rotation) const
{
  return m_pEventHandler != nullptr && m_pEventHandler->GetMotionTrackerPosition(trackerID, offset, rotation);
}

void CImageGeneratorEventMessenger::SendCreateEntityMessage(const sbio::ig::entity::SCreateEntityMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnCreateEntityMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendDestroyEntityMessage(const sbio::ig::entity::SDestroyEntityMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnDestroyEntityMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendUpdateTopLevelEntityTransformMessage(const sbio::ig::entity::SUpdateTopLevelEntityTransformMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnUpdateTopLevelEntityTransformMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendUpdateChildEntityTransformMessage(const sbio::ig::entity::SUpdateChildEntityTransformMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnUpdateChildEntityTransformMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendSetEntityAttachedMessage(const sbio::ig::entity::SSetEntityAttachedMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnSetEntityAttachedMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendSetEntityActiveMessage(const sbio::ig::entity::SSetEntityActiveMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnSetEntityActiveMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendSetEntityUnattachedMessage(const sbio::ig::entity::SSetEntityUnattachedMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnSetEntityUnattachedMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendSetEntityComponentStateMessage(const sbio::ig::entity::SSetEntityComponentStateMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnSetEntityComponentStateMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendUpdateArticulatedPartTransformMessage(const sbio::ig::entity::SUpdateArticulatedPartTransformMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnUpdateArticulatedPartTransformMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendSetArticulatedPartVisibleMessage(const sbio::ig::entity::SSetArticulatedPartVisibleMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnSetArticulatedPartVisibleMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendSetEntityAlphaMessage(const sbio::ig::entity::SSetEntityAlphaMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnSetEntityAlphaMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendSetEntityCollisionDetectionEnabledMessage(const sbio::ig::entity::SSetEntityCollisionDetectionEnabledMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnSetEntityCollisionDetectionEnabledMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendLineOfSightSegmentRequestBasicMessage(const sbio::ig::terrain::SLineOfSightSegmentRequestBasicMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnLineOfSightSegmentRequestBasicMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendLineOfSightSegmentRequestExtendedMessage(const sbio::ig::terrain::SLineOfSightSegmentRequestExtendedMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnLineOfSightSegmentRequestExtendedMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendLineOfSightVectorRequestBasicMessage(const sbio::ig::terrain::SLineOfSightVectorRequestBasicMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnLineOfSightVectorRequestBasicMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendLineOfSightVectorRequestExtendedMessage(const sbio::ig::terrain::SLineOfSightVectorRequestExtendedMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnLineOfSightVectorRequestExtendedMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendHeightAboveTerrainRequestMessage(const sbio::ig::terrain::SHeightAboveTerrainRequestMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnHeightAboveTerrainRequestMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendHeightOfTerrainRequestMessage(const sbio::ig::terrain::SHeightOfTerrainRequestMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnHeightOfTerrainRequestMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendTerrestrialSurfaceConditionsChangedMessage()
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnTerrestrialSurfaceConditionsChangedMessage();
  }
}

void CImageGeneratorEventMessenger::SendSetRegionalTerrainSurfaceComponentStateMessage(const sbio::ig::terrain::SSetRegionalTerrainSurfaceComponentStateMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnSetRegionalTerrainSurfaceComponentStateMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendSetGlobalTerrainComponentStateMessage(const sbio::ig::terrain::SSetGlobalTerrainComponentStateMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnSetGlobalTerrainComponentStateMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendSetCollisionDetectionSegmentEnabledMessage(const sbio::ig::physics::SSetCollisionDetectionSegmentEnabledMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnSetCollisionDetectionSegmentEnabledMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendSetCollisionDetectionSegmentMessage(const sbio::ig::physics::SSetCollisionDetectionSegmentMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnSetCollisionDetectionSegmentMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendCreateCollisionDetectionSegmentMessage(const sbio::ig::physics::SCreateCollisionDetectionSegmentMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnCreateCollisionDetectionSegmentMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendCreateCollisionVolumeSphereMessage(const sbio::ig::physics::SCreateCollisionVolumeSphereMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnCreateCollisionVolumeSphereMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendCreateCollisionVolumeCuboidMessage(const sbio::ig::physics::SCreateCollisionVolumeCuboidMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnCreateCollisionVolumeCuboidMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendSetCollisionVolumeEnabledMessage(const sbio::ig::physics::SSetCollisionVolumeEnabledMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnSetCollisionVolumeEnabledMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendSetCollisionVolumeMessage(const sbio::ig::physics::SSetCollisionVolumeMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnSetCollisionVolumeMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendDestroyCollisionVolumeMessage(const sbio::ig::physics::SDestroyCollisionVolumeMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnDestroyCollisionVolumeMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendUpdateAttachedCameraTransformMessage(const sbio::ig::view::SUpdateAttachedCameraTransformMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnUpdateAttachedCameraTransformMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendSetCameraAttachedToEntityMessage(const sbio::ig::view::SSetCameraAttachedToEntityMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnSetCameraAttachedToEntityMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendSetCameraUnattachedMessage(const sbio::ig::view::SSetCameraUnattachedMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnSetCameraUnattachedMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendBringCameraToTopMessage(const sbio::ig::view::SBringCameraToTopMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnBringCameraToTopMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendSetCameraProjectionMessage(const sbio::ig::view::SSetCameraProjectionMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnSetCameraProjectionMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendSetViewComponentStateMessage(const sbio::ig::view::SSetViewComponentStateMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnSetViewComponentStateMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendSetViewGroupComponentStateMessage(const sbio::ig::view::SSetViewGroupComponentStateMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnSetViewGroupComponentStateMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendLoadDatabaseMessage(const sbio::ig::database::SLoadDatabaseMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnLoadDatabaseMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendUnloadDatabaseMessage()
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnUnloadDatabaseMessage();
  }
}

void CImageGeneratorEventMessenger::SendSetAnimationDirectionMessage(const sbio::ig::animation::SSetAnimationDirectionMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnSetAnimationDirectionMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendSetAnimationLoopModeMessage(const sbio::ig::animation::SSetAnimationLoopModeMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnSetAnimationLoopModeMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendSetAnimationSpeedMessage(const sbio::ig::animation::SSetAnimationSpeedMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnSetAnimationSpeedMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendSetAnimationAlphaMessage(const sbio::ig::animation::SSetAnimationAlphaMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnSetAnimationAlphaMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendStopEntityAnimationMessage(const sbio::ig::animation::SStopEntityAnimationMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnStopEntityAnimationMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendStopAtCurrentFrameEntityAnimationMessage(const sbio::ig::animation::SStopAtCurrentFrameEntityAnimationMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnStopAtCurrentFrameEntityAnimationMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendPauseEntityAnimationMessage(const sbio::ig::animation::SPauseEntityAnimationMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnPauseEntityAnimationMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendPlayEntityAnimationMessage(const sbio::ig::animation::SPlayEntityAnimationMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnPlayEntityAnimationMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendRestartEntityAnimationMessage(const sbio::ig::animation::SRestartEntityAnimationMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnRestartEntityAnimationMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendCreateSymbolTextMessage(const sbio::ig::symbol::SCreateSymbolTextMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnCreateSymbolTextMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendUpdateSymbolTextMessage(const sbio::ig::symbol::SUpdateSymbolTextMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnUpdateSymbolTextMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendSetSymbolColorMessage(const sbio::ig::symbol::SSetSymbolColorMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnSetSymbolColorMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendDestroySymbolMessage(const sbio::ig::symbol::SDestroySymbolMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnDestroySymbolMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendCreateSymbolCircleMessage(const sbio::ig::symbol::SCreateSymbolCircleMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnCreateSymbolCircleMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendUpdateSymbolCircleMessage(const sbio::ig::symbol::SUpdateSymbolCircleMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnUpdateSymbolCircleMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendUpdateSymbolCircleElementMessage(const sbio::ig::symbol::SUpdateSymbolCircleElementMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnUpdateSymbolCircleElementMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendUpdateSymbolCircleFilledMessage(const sbio::ig::symbol::SUpdateSymbolCircleFilledMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnUpdateSymbolCircleFilledMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendUpdateSymbolCircleFilledElementMessage(const sbio::ig::symbol::SUpdateSymbolCircleFilledElementMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnUpdateSymbolCircleFilledElementMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendCreateSymbolTexturedCircleMessage(const sbio::ig::symbol::SCreateSymbolTexturedCircleMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnCreateSymbolTexturedCircleMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendUpdateSymbolTexturedCircleMessage(const sbio::ig::symbol::SUpdateSymbolTexturedCircleMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnUpdateSymbolTexturedCircleMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendUpdateTexturedCircleMessage(const sbio::ig::symbol::SUpdateTexturedCircleMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnUpdateTexturedCircleMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendCreateSymbolPolygonMessage(const sbio::ig::symbol::SCreateSymbolPolygonMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnCreateSymbolPolygonMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendUpdateSymbolPolygonMessage(const sbio::ig::symbol::SUpdateSymbolPolygonMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnUpdateSymbolPolygonMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendSetSymbolPolygonVertexMessage(const sbio::ig::symbol::SSetSymbolPolygonVertexMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnSetSymbolPolygonVertexMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendCreateSymbolTexturedPolygonMessage(const sbio::ig::symbol::SCreateSymbolTexturedPolygonMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnCreateSymbolTexturedPolygonMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendUpdateSymbolTexturedPolygonMessage(const sbio::ig::symbol::SUpdateSymbolTexturedPolygonMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnUpdateSymbolTexturedPolygonMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendSetSymbolTexturedPolygonVertexMessage(const sbio::ig::symbol::SSetSymbolTexturedPolygonVertexMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnSetSymbolTexturedPolygonVertexMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendUpdateEntityBillboardSymbolSurfaceMessage(const sbio::ig::symbol::SUpdateEntityBillboardSymbolSurfaceMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnUpdateEntityBillboardSymbolSurfaceMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendCreateSymbolSurfaceMessage(const sbio::ig::symbol::SCreateSymbolSurfaceMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnCreateSymbolSurfaceMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendDestroySymbolSurfaceMessage(const sbio::ig::symbol::SDestroySymbolSurfaceMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnDestroySymbolSurfaceMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendUpdateSymbolSurfaceMessage(const sbio::ig::symbol::SUpdateSymbolSurfaceMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnUpdateSymbolSurfaceMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendUpdateViewSymbolSurfaceMessage(const sbio::ig::symbol::SUpdateViewSymbolSurfaceMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnUpdateViewSymbolSurfaceMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendSetSymbolVisibleMessage(const sbio::ig::symbol::SSetSymbolVisibleMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnSetSymbolVisibleMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendSetSymbolAttachedMessage(const sbio::ig::symbol::SSetSymbolAttachedMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnSetSymbolAttachedMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendSetSymbolUnattachedMessage(const sbio::ig::symbol::SSetSymbolUnattachedMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnSetSymbolUnattachedMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendSetSymbolSurfaceMessage(const sbio::ig::symbol::SSetSymbolSurfaceMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnSetSymbolSurfaceMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendClearSymbolSurfaceMessage(const sbio::ig::symbol::SClearSymbolSurfaceMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnClearSymbolSurfaceMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendSetTopLevelSymbolTransformMessage(const sbio::ig::symbol::SSetTopLevelSymbolTransformMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnSetTopLevelSymbolTransformMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendSetChildSymbolTransformMessage(const sbio::ig::symbol::SSetChildSymbolTransformMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnSetChildSymbolTransformMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendUpdateSymbolMessage(const sbio::ig::symbol::SUpdateSymbolMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnUpdateSymbolMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendSetSymbolComponentStateMessage(const sbio::ig::symbol::SSetSymbolComponentStateMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnSetSymbolComponentStateMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendSetSymbolSurfaceComponentStateMessage(const sbio::ig::symbol::SSetSymbolSurfaceComponentStateMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnSetSymbolSurfaceComponentStateMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendCreateSymbolFromTemplateMessage(const sbio::ig::symbol::SCreateSymbolFromTemplateMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnCreateSymbolFromTemplateMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendUpdateCelestialSphereMessage(const sbio::ig::celestial::SUpdateCelestialSphereMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnUpdateCelestialSphereMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendUpdateDateTimeMessage(const sbio::ig::celestial::SUpdateDateTimeMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnUpdateDateTimeMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendSetCelestialSphereComponentStateMessage(const sbio::ig::celestial::SSetCelestialSphereComponentStateMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnSetCelestialSphereComponentStateMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendUpdateSensorMessage(const sbio::ig::sensor::SUpdateSensorMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnUpdateSensorMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendUpdateSensorComponentMessage(const sbio::ig::sensor::SUpdateSensorComponentMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnUpdateSensorComponentMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendCreateMotionTrackerViewMessage(const sbio::ig::sensor::SCreateMotionTrackerViewMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnCreateMotionTrackerViewMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendCreateMotionTrackerViewGroupMessage(const sbio::ig::sensor::SCreateMotionTrackerViewGroupMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnCreateMotionTrackerViewGroupMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendSetMotionTrackerMessage(const sbio::ig::sensor::SSetMotionTrackerMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnSetMotionTrackerMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendSetAtmosphereEnabledMessage(const sbio::ig::atmosphere::SSetAtmosphereEnabledMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnSetAtmosphereEnabledMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendSetAtmosphereMessage(const sbio::ig::atmosphere::SSetAtmosphereMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnSetAtmosphereMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendSetWeatherMessage(const sbio::ig::atmosphere::SSetWeatherMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnSetWeatherMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendSetRegionalLayeredWeatherComponentStateMessage(const sbio::ig::atmosphere::SSetRegionalLayeredWeatherComponentStateMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnSetRegionalLayeredWeatherComponentStateMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendSetGlobalLayeredWeatherComponentStateMessage(const sbio::ig::atmosphere::SSetGlobalLayeredWeatherComponentStateMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnSetGlobalLayeredWeatherComponentStateMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendSetAtmosphereComponentStateMessage(const sbio::ig::atmosphere::SSetAtmosphereComponentStateMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnSetAtmosphereComponentStateMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendSetMaritimeSurfaceConditionsMessage(const sbio::ig::ocean::SSetMaritimeSurfaceConditionsMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnSetMaritimeSurfaceConditionsMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendSetRegionMaritimeComponentStateMessage(const sbio::ig::ocean::SSetRegionMaritimeComponentStateMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnSetRegionMaritimeComponentStateMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendSetGlobalMaritimeComponentStateMessage(const sbio::ig::ocean::SSetGlobalMaritimeComponentStateMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnSetGlobalMaritimeComponentStateMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendSetEarthReferenceModelMessage(const sbio::ig::earth::SSetEarthReferenceModelMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnSetEarthReferenceModelMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendSetEventComponentStateMessage(const sbio::ig::system::SSetEventComponentStateMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnSetEventComponentStateMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendSetSystemComponentStateMessage(const sbio::ig::system::SSetSystemComponentStateMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnSetSystemComponentStateMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendHostConnectedMessage(const sbio::ig::network::SHostConnectedMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnSetHostConnectedMessage(data);
  }
}

void CImageGeneratorEventMessenger::SendHostDisconnectedMessage(const sbio::ig::network::SHostDisconnectedMessage& data)
{
  if (m_pEventHandler != nullptr)
  {
    m_pEventHandler->OnSetHostDisconnectedMessage(data);
  }
}

//The source code in this file is licensed under the MIT License. See the LICENSE text file for full terms.
//Refer all inquiries to sales@simblocks.io
//Copyright SimBlocks LLC 2016-2026
